### ISSUE TITLE
[FEATURE REQUEST] Handler function middleware

### ISSUE THREAD

**Issue by rugwirobaker** [hibiken/asynq#104]
**Is your feature request related to a problem? Please describe.**
Do plan to support middleware functions that behave the same way for example gorilla mux.Middware do? If not how do logging??

**Comment by hibiken** [comment]
@rugwirobaker Thanks for this feature request!

Could you provide an example code for a potential API for middleware support?

Alternatively, can you simply write a middleware function and wrap your handlers with that middleware?

```go
func loggingMiddleware(h asynq.Handler) asynq.Handler {
    return asynq.HandlerFunc(func(ctx context.Context, t *asynq.Task) error {
        // log something before handler processes the task
        h.ProcessTask(ctx, t)
        // log something after handler processed the task
    })
}

mux := asynq.ServeMux()
mux.HandleFunc("something", loggingMiddleware(myHandler))
```

would that work? Or should the package offer better support for middleware chain?

**Comment by rugwirobaker** [comment]
For most use cases this works fine but in cases where you have a lot of middleware functions having something like:
`mux.Use(someMiddlware) ` or  `mux.Add(someMiddleware)` it would help avoid the clutter.

**Comment by hibiken** [comment]
Ok that makes sense.
Let's add `Use` method to add middlewares to the chain, similar to  [gorilla/mux#Route.Use](https://godoc.org/github.com/gorilla/mux#Router.Use). The method should a variadic function that takes any number of middleware functions. They  should be executed in the order that they are applied.

Example:
```go
mux := asynq.ServeMux()
mux.Use(loggingMiddleware)
mux.HandleFunc("something", myHandler)
```
