### ISSUE TITLE
[FEATURE REQUEST] Show latency of each queue in CLI

### ISSUE THREAD

**Issue by hibiken** [hibiken/asynq#124]
**Is your feature request related to a problem? Please describe.**
Currently, we can only see how many tasks have been enqueued in each queue using the CLI. 
It'd be better if we can show the latency of each queue in the output so that user can tell when was the oldest task in the queue was enqueued.

**Describe the solution you'd like**
Show the latency within the `stats` command output.

**Describe alternatives you've considered**
None for now.

**Additional context**
None for now.

**Comment by zhaolion** [comment]
An idea:

- Provide middleware of server side or client side, deliver performnace data to promethues  and show it in Grafana. 🤔

**Comment by hibiken** [comment]
@zhaolion interesting! Integration with Prometheus seems like a great thing to have. 
Let me look into this as part of https://github.com/hibiken/asynq/projects/2 👍

**Comment by hibiken** [comment]
Moved to #246
