### ISSUE TITLE
[FEATURE_REQUEST] Add support for Redis Cluster mode

### ISSUE THREAD

**Issue by zhouyang8304** [hibiken/asynq#138]
startJob.Enqueue enqueue QTTMemberID:702303,OutKey:user_main-coin_to_sub_702303_1587398400 Error:ERR 'EVALSHA' command keys must in same slot

Dequeue error: ERR Error running script (call to f_119a32ad4f4ac4f23fba1b8be91aacd2948feb88): @user_script:4: @user_script: 4: Lua script attempted to access a non local key in a cluster node

**Comment by hibiken** [comment]
@zhouyang8304 thank you for opening an issue!

Are you trying to use Asynq with Redis **cluster**?

**Comment by zhouyang8304** [comment]
yes 
im use Asynq on  Redis cluster 
get error 
 Error:ERR 'EVALSHA' command keys must in same slot 
How to solve the error

**Comment by zhouyang8304** [comment]
redis version 5.0.5

**Comment by hibiken** [comment]
I see. Asynq currently doesn't support Redis cluster. 
It currently supports **Single Node Redis** or **Redis Sentinels**. 

I need to investigate how to make it work for Redis cluster. It is an absolute requirement for you to use cluster mode? If so, I can prioritize this bug.

**Comment by zhouyang8304** [comment]
ok thanks

**Comment by hibiken** [comment]
I'll change this to a feature request. Please let me know if this is a blocker for you :)
