### ISSUE TITLE
[QUESTION] Way to determine a task is a retry

### ISSUE THREAD

**Issue by jimmy-ho** [hibiken/asynq#154]
Is there an easy way to determine if the current task being processed is a retry? It is not in the context I guess passed to ProcessTask, would be nice to have it in the Task perhaps.

This is useful if I have already completed some set of action, but then need to retry some aspect that failed - unless I need to store some relationship that a particular task failed and thus subsequent will be a retry?

I prefer I do not need to store this, as I see in redis we already are storing the number of retries which can be used as a determinant.

Maybe I have missed some means to be able to just get this information somehow?

**Comment by hibiken** [comment]
Great question and thanks for opening this issue.

Current APIs don't offer an ability to determine whether a `Task` passed to your `Handler` is a retry task. 

I think it makes total sense to put task metadata such as `RetryCount` in the `context` Value. 
I'll do a little bit of research and update this thread with a proposal 👍

**Comment by hibiken** [comment]
## Proposal

Here's my initial proposal. Please let me know if you have any thoughts or feedback 😃 

 Export functions to extract task metadata  from context:

`GetTaskID(ctx context.Context) (id string, ok bool)`

`GetRetryCount(ctx context.Context) (n int, ok bool)`

`GetMaxRetry(ctx context.Context) (n int, ok bool)`


### Example 

```go
func (h *MyHandler) ProcessTask(ctx context.Context, t *asynq.Task) error {
    retried, ok := asynq.GetRetryCount(ctx)
    if ok {
        log.Printf("this task has been retried for %d times", retried)
    }
    
    // ... rest of the handler logic
}
```

**Comment by jimmy-ho** [comment]
@hibiken looks good to me, thanks for your time in looking into this.
