### ISSUE TITLE
[FEATURE REQUEST] WebUI of server states (like sidekiq's UI)

### ISSUE THREAD

**Issue by zhaolion** [hibiken/asynq#167]
We could offer a cmd for serving a comprehensive Web UI for management and monitoring 

**Describe the solution you'd like**
maybe we can add a sub cmd in asynq. eg. `asynq webui`.

eg. https://raw.githubusercontent.com/mperham/sidekiq/master/examples/web-ui.png

**Comment by zhaolion** [comment]
> Yes, this is definitely in the project's roadmap!
> 
> Issue #50 is related to this one (I think it's good time to start working on this since the internal has been stable for a while now). I haven't decided whether we want to have that as a command in the CLI or standalone thing in a separate repo.
> 
> Thanks for opening this issue. I'll prioritize this one because it adds much value to the users.

The plan of standalone thing in a separate repo maybe a better choice. I have a sugguestion, maybe we can rename pkg `asynq/internal` as `asynq/pkg`, so a standalone server connect to asynq/server or redis by using `internal/rdb`

**Comment by hibiken** [comment]
I see. I had similar idea in mind with #50 . Currently we have `inspect.go` file in the `internal/rdb` package, but I'd like to extract that out into its own package and make its API public (other parts of `internal` packages are not public API, so they need to stay under the directory named `internal`). 

I haven't settled on the package name yet, but I'm leaning towards `github.com/hibiken/asynq/x/inspect` or `github.com/hibiken/asynq/pkg/inspect` or `github.com/hibiken/asynq/contrib/inspect`

**Comment by zhaolion** [comment]
> I see. I had similar idea in mind with #50 . Currently we have `inspect.go` file in the `internal/rdb` package, but I'd like to extract that out into its own package and make its API public (other parts of `internal` packages are not public API, so they need to stay under the directory named `internal`).
> 
> I haven't settled on the package name yet, but I'm leaning towards `github.com/hibiken/asynq/x/inspect` or `github.com/hibiken/asynq/pkg/inspect` or `github.com/hibiken/asynq/contrib/inspect`

Got it. `github.com/hibiken/asynq/x/inspect` is more interesting 🤣

**Comment by rrupesh** [comment]
@hibiken would you consider having the CMD functionality as part of `async.Client`? It would really be handy to keep track of all the jobs that are running. For example, I'd want to pause all jobs or selectively cancel / restart a job. Having this functionality part of `client` would be an easy integration with the existing code.

**Comment by hibiken** [comment]
@rrupesh thanks for commenting! 
Actually I'm currently working on it 😄 All the functionality you get with asynq CLI will be available though a new type called `Inspector`. This change should be in the next release v0.11.0.

**Comment by rrupesh** [comment]
@hibiken Thank you very much! I was using `gocraft` until this morning. I learnt about your awesome work and it took me about 30 mins to literally migrate from `gocraft` to `asynq`. Almost a drop-in replacement. Btw, do you have a donate / buy me a coffee or similar link? lmk!

**Comment by hibiken** [comment]
@rrupesh thanks! I may consider adding Github support button to this repo eventually (e.g. when I commit to v1 compatibility). But for now I enjoy working on this project and it's really rewarding to hear feedback on it from people like you. So thank you for your feedback!!

**Comment by mingrammer** [comment]
I'm looking forward to this feature :) Thank you for your efforts.

**Comment by hibiken** [comment]
I'm happy to announce the initial release of the web UI 🎉
Please checkout [Asynqmon](https://github.com/hibiken/asynqmon) repo and follow the installation instructions. 

Feedbacks are appreciated!

**Comment by zhaolion** [comment]
> I'm happy to announce the initial release of the web UI 🎉
> Please checkout [Asynqmon](https://github.com/hibiken/asynqmon) repo and follow the installation instructions.
> 
> Feedbacks are appreciated!

Thanks for your efforts. Will be used soon 🆒
