### ISSUE TITLE
Support RedisCluster client

### ISSUE THREAD

**Issue by cemremengu** [hibiken/asynq#182]
First of thanks for the great work! I would like to know if it is technically possible to support Redis cluster or it is out of the scope of the project?

**Comment by hibiken** [comment]
@cemremengu thank you! 
It's definitely on the project's roadmap but currently it only supports Single Redis node or connecting via Redis Sentinels. 

Thank you for opening this issue though, seems like Redis Cluster support is something that people are interested in #138 .
I can start looking into this more once I finish my current projects 👍
