### ISSUE TITLE
[FEATURE REQUEST] make inspector non-internal package

### ISSUE THREAD

**Issue by 3timeslazy** [hibiken/asynq#187]
Hello! Thanks for your project!

**Is your feature request related to a problem? Please describe.**
There is a need to interact with asynq over HTTP and not through the CLI. This is not possible now because RDB is an internal package.

**Describe the solution you'd like**
Move RDB into `pkg`

**Comment by hibiken** [comment]
Thanks for opening the issue!


There's a public API from [`Inspector`](https://godoc.org/github.com/hibiken/asynq#Inspector) type that exports a subset of RDB functionality. 
Let me know if that doesn't meet your need, we can add more functionality to `Inspector` 👍

**Comment by hibiken** [comment]
@3timeslazy I'm closing this. Please let me know if the current Inspector API meet your needs 👍

**Comment by 3timeslazy** [comment]
@hibiken thanks for your help!
