### ISSUE TITLE
[FEATURE REQUEST] Shared and Dedicated Queue Workers with strategy

### ISSUE THREAD

**Issue by itsursujit** [hibiken/asynq#196]
Shared Queue Workers:
- As a developer, I would define all required queues (with priorities), no. of workers required for each queues
- Apply different strategies to dispatch to queues with appropriate priorities. 
   ROUND-ROBIN strategy - Whichever queue is free, send to that queue irrespective of queue priorities, 
   WEIGHTED strategy - Send to queue with appropriate queue based on messages. High volume messages would go with high priority queue,
   CUSTOM strategy - Admin defines the strategy for user. If userA is set to high priority, his messages will go to high priority queue

Probably making use of `mux.Handle("queue", handler)`

Dedicate Queue Workers:
 - Everything from Shared Queue workers.
 - Queues and workers are created per user dedicated to them only.
   
Probably making use of `mux.HandleFunc("queue:12", handler)`

**Comment by itsursujit** [comment]
https://github.com/hibiken/asynq/issues/194

**Comment by hibiken** [comment]
You could use `Inspector.CurrentStats` to inspect the size of the queue. You can implement strategies listed above in your application code. I don't think we want to implement this at this package level (at least for now).
