### ISSUE TITLE
[FEATURE REQUEST] Filter or intercept the task on queue and do operations like Stop/Pause/Resume tasks

### ISSUE THREAD

**Issue by sujit-baniya** [hibiken/asynq#197]
In Shared or Dedicated queue, it's good to have filter feature for tasks on queue. This feature will allow to do operations like Stop/Pause/Resume/Stats for the subset of tasks on queue.

By filter or Intercept the task, I mean before/after the task is put on the queue and consumer has still not consumed the task, I could filter the list of tasks by payload and do operations like Delay such task, Stop them or pause or resume them.

Use-Case:
Users are sending tasks to a dynamically created queue. As an admin, I could filter and group the list of tasks by any field in the payload and view the stats of tasks on queue. This would help me control the tasks per user or payload

**Comment by itsursujit** [comment]
https://github.com/hibiken/asynq/issues/194

**Comment by hibiken** [comment]
Maybe not exactly what you need, but you can implement your `Handler` to do a pre-check.

If you are using `ServeMux`, you can accomplish this by adding a middleware, which will be called for all tasks regardless of its type.

Example:
```go
func precheckMiddleware(h asynq.Handler) asynq.Handler {
    return asynq.HandlerFunc(func(ctx context.Context, t *asynq.Task) error {
        // do precheck and return error if you need to skip this task.
        if (/* some precheck condition */) {
            return fmt.Errorf("some error message")
        }
        // otherwise, invoke handler as normal.
        return h.ProcessTask(ctx, t)
    })
} 

// ...

mux := asynq.NewServeMux()
mux.Use(precheckMiddleware)
```

**Comment by hibiken** [comment]
Closing this issue. Seems stale.
