### ISSUE TITLE
[FEATURE REQUEST] UnRegister function to unregister task entries

### ISSUE THREAD

**Issue by sujit-baniya** [hibiken/asynq#204]
New Scheduler functionality is quite awaited feature. Maybe you would consider following functionalities:

- `RemoveEntry` or `UnRegister` function to remove entry by `entryID`. So instead of stopping cron and manually removing the entries maybe it could be done with a function
- View Entries by time period. For e.g. Entries for `@every 30s`, Entries for `@daily`

Also this will allow possibility to handle CRON via REST or any other services

**Comment by DemonTPx** [comment]
Hi @hibiken, Would you please reconsider reopening and merging the `Unregister` method PR?

In our project we would like to be able to change the cronspec of existing schedulers. This could be achieved by being able to unregister the scheduled task and rescheduling it.

Your PR seemed to me of perfect use in our project.

**Comment by hibiken** [comment]
@DemonTPx thanks for the comment. 
I'll revisit this feature again this week 👍
