### ISSUE TITLE
[FEATURE REQUEST] JSON output flag for asynq stats

### ISSUE THREAD

**Issue by rverton** [hibiken/asynq#206]
To monitor the asynq queue, it would be nice to periodically retrieve stats (like the `asynq stats` command currently does), but in a format which can be piped into monitoring tools. 

A simple and easy way to do this would be to add a `--json` flag to `asynq stats` which outputs all gathered stats as json. This stats can then periodically be retrieved (with tools like Telegraf) and then displayed in Grafana.

**Comment by hibiken** [comment]
Thanks for opening this issue!

Seems like a good option to have. I'll include this change in the next release.

**Comment by c-nv-s** [comment]
definitely in favor of this feature too!

**Comment by c-nv-s** [comment]
@hibiken  any update on this request?

**Comment by hibiken** [comment]
@c-nv-s thank you for the comment! 
Sorry, this feature work has been de-prioritized because I had other features to work on. I'm currently working on metrics related work, so I may be able to work on this soon.

But if anyone's interested, feel free to open a PR for this 👍

**Comment by mdibaiee** [comment]
Hello 👋 
I just saw this issue and thought it was easy enough to fix in my spare time, so I just created a PR. Happy to apply any feedback you have on it.

P.S.: Happy new year!
