### ISSUE TITLE
[FEATURE REQUEST] is there any benchmark result for asynq?

### ISSUE THREAD

**Issue by notech** [hibiken/asynq#212]

**Comment by notech** [comment]
i find a lot of lua script in rdb.go,
such as 
```
if redis.call("LREM", KEYS[1], 0, ARGV[1]) == 0 then
  return redis.error_reply("NOT FOUND")
end
if redis.call("ZREM", KEYS[2], ARGV[1]) == 0 then
  return redis.error_reply("NOT FOUND")
end
redis.call("ZADD", KEYS[3], ARGV[3], ARGV[2])
local n = redis.call("INCR", KEYS[4])
if tonumber(n) == 1 then
	redis.call("EXPIREAT", KEYS[4], ARGV[4])
end
local m = redis.call("INCR", KEYS[5])
if tonumber(m) == 1 then
	redis.call("EXPIREAT", KEYS[5], ARGV[4])
end
return redis.status_reply("OK")
```

**Comment by hibiken** [comment]
@notech Thank you opening an issue to ask this question!

You can run all of the benchmark tests in this package with

```
go test -run=^$ -bench=.  github.com/hibiken/asynq 
```

You can see the details of the benchmark test in [`benchmark_test.go`](https://github.com/hibiken/asynq/blob/master/benchmark_test.go) file.
Also, you can pass flags to the above command to specify redis server address, redis db number, use redis cluter etc. Check out all available test flags [here](https://github.com/hibiken/asynq/blob/8d6e4167abbcb435334c7a156457e1a1f832980e/asynq_test.go#L37).
