### ISSUE TITLE
[FEATURE REQUEST] Allow handlers to fail a task permanently (no retry)

### ISSUE THREAD

**Issue by bojanz** [hibiken/asynq#221]
**Is your feature request related to a problem? Please describe.**
Asynq supports automatically retrying tasks. In some cases, it is obvious to the handler that a task can't ever be completed successfully. The handler currently has two ways to handle this:
- Return an error, and go through the next N retries.
- Return nil and stop processing.

Returning nil has the downside of not keeping the task "dead", so it becomes invisible to the CLI and the future web UI.

**Describe the solution you'd like**
I'd like to be able to return an error such as asynq.NoRetryError(msg) which would stop execution and mark the task as dead.

**Describe alternatives you've considered**
Returning nil and flipping a "permanently failed" boolean on the object being processed works as an alternative. This feature request is a "nice to have", but feels reasonable for a queue to support.

**Comment by hibiken** [comment]
@bojanz Thank you for opening this issue, this is definitely much-needed feature. 

The solution you suggested sounds reasonable to me. `Handler` can return some sentinel error type to indicate that the task doesn't need to be retried. 
I'll include this change in the next version release (should be in a week or two if all goes well).

**Comment by hibiken** [comment]
Closed via #226
