### ISSUE TITLE
[BUG] Panics lack context

### ISSUE THREAD

**Issue by bojanz** [hibiken/asynq#222]
**Describe the bug**
Asynq's panic handling only logs the error, without any stack trace information:
```
	defer func() {
		if x := recover(); x != nil {
			err = fmt.Errorf("panic: %v", x)
		}
	}()
```
This can make it difficult to debug a panic, which is often generic (e.g. "runtime error: invalid memory address or nil pointer dereference"). 

Could we at least add the triggering line and file to the output? That would look something like this:
```
	defer func() {
		if x := recover(); x != nil {
                        // Skip the first frame (the panic func itself).
                        _, file, line, _ := runtime.Caller(1)
                        // The panic came from the runtime, most likely due to incorrect
	                // map/slice usage. The parent frame should have the real trigger.
	                if strings.HasPrefix(file, "runtime/") {
		                _, file, line, _ = runtime.Caller(2)
	                }
			err = fmt.Errorf("panic [%v:%v]: %v", file, line, x)
		}
	}()
```
Since this is still just a suggestion, I did not test the runtime.Caller() line to see if we're skipping the right number of stacks, the numbers might need to be bumped by 1.

**Comment by hibiken** [comment]
@bojanz  Thank you for pointing this out!
I'll see if we can include more meaningful context in the error itself. 
At a minimum we should be logging the panic info when we recover from a panic.
