### ISSUE TITLE
[BUG] Scheduler is too chatty

### ISSUE THREAD

**Issue by bojanz** [hibiken/asynq#223]
Scheduler logs to the INFO level every time it (re)schedules a task. This fills up the logs at the INFO level, forcing us to bump the reporting level to WARN, which is not ideal.

Could we make this log to the DEBUG level instead:
``` 
	j.logger.Infof("scheduler enqueued a task: %+v", res)
```
It feels like it fits better with the other queue server log entries, where INFO tells us that the service is starting/stopping, but stays silent about actual tasks.

Happy to send in a PR if you agree with the change.

**Comment by hibiken** [comment]
Good point. I agree with a that.
PR would be welcome!
