### ISSUE TITLE
[FEATURE REQUEST] Allow grouping middleware

### ISSUE THREAD

**Issue by bojanz** [hibiken/asynq#224]
**Is your feature request related to a problem? Please describe.**
Asynq's processors resemble HTTP handlers, down to the multiplexer. This was a great choice, and makes the API easy to use.

Right now the multiplexer allows adding middleware via mux.Use(), but that middleware is always global. There is no way to declare middleware only for a certain group of tasks. If some tasks process orders and some tasks process products, it gets tricky to have a middleware that loads an order and puts it in the context, and a middleware that loads a product and puts it in the context.

**Describe the solution you'd like**
My suggestion is to copy the approach that routers like Chi take, and also offer a Group() method.

This would allow code like:
```
group := mux.Group()
group.Use(productMiddleware)
group.HandleFunc("product:update", handler)

group := mux.Group()
group.Use(orderMiddleware)
group.HandleFunc("order:refund", handler)
```

This is deep in the "nice to have" territory, just figured it's worth suggesting.

**Comment by hibiken** [comment]
@bojanz Thank you for opening this issue! (Your questions and suggestions are always spot-on!)

I personally have not used `chi` but this API is definitely nice to have. Especially as your Handler grows, this grouping of task handlers is going to be very helpful.

Let's implement this feature. Feel free to create a PR if you are interested in implementing 👍

**Comment by bojanz** [comment]
Thanks, I appreciate that.

 I can look into this in about a week. If anyone needs it before then, feel free to go around me.

**Comment by hibiken** [comment]
Actually I believe you can accomplish this by composing multiple `ServeMux` . Since `ServeMux` performs prefix matching, as long as each "group" has the same type prefix, you can group them.

Example:
```go
productHandlers := asynq.NewServeMux()
productHandlers.Use(productMiddleware)
productHandlers.HandleFunc("product:update", productUpdateTaskHandler)

orderHandlers := asynq.NewServeMux()
orderHandler.Use(orderMiddleware)
orderHandlers.HandleFunc("order:refund", orderRefundTaskHandler)

// Top level handler
mux := asynq.NewServeMux()
mux.Use(someGlobalMiddleware)
mux.Handle("product:", productHandlers)
mux.Handle("order:", orderHandlers)
```

Let me know if this solution works!

**Comment by bojanz** [comment]
That works wonderfully, updated my code to do that instead of checking the task type in middleware. Thank you!

I guess all we need is a bit of docs in the wiki for this, then?

**Comment by hibiken** [comment]
Awesome! I'll keep this issue open as a reminder to update the wiki 👍

**Comment by xingshanghe** [comment]
Have you got it done?expecting!

**Comment by hibiken** [comment]
Done! See the documentation [here](https://github.com/hibiken/asynq/wiki/Handler-Deep-Dive#grouping-middlewares).
