### ISSUE TITLE
[FEATURE REQUEST] Filter tasks by payload fields

### ISSUE THREAD

**Issue by sujit-baniya** [hibiken/asynq#230]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
With filtering tasks by payload fields in a queue, I want to do operations on specific tasks only. The operations could be listing such tasks, deleting them, archiving them, etc

**Comment by hibiken** [comment]
Thank you for opening this issue!

I can see the value in this feature, but it's non-trivial to implement this filter (efficient filter operation).
I'll look into how we can support filtering and searching of tasks and hopefully include this feature in the future release.

**Comment by hibiken** [comment]
Moved to #246
