### ISSUE TITLE
[FEATURE REQUEST] Pass default queue name when initializing client

### ISSUE THREAD

**Issue by mingrammer** [hibiken/asynq#233]
**Is your feature request related to a problem? Please describe.**

No, but it is for convenience. Passing the queue name when enqueue tasks every time is too cumbersome. So I'd like to suggest a feature described below.

**Describe the solution you'd like**

It would be good to pass the default queue name when initializing the `asynq.Client` like `asynq.Server` initialization. (If `ClientOption` is added, the current `Option` should be renamed to `ServerOption` I think)

```go
client := asynq.NewClient(r, asynq.ClientOption{
    Queue: "sync-event", // If don't pass option, `default` will be used.
})
defer client.Close()

t := asynq.NewTask("sync:user", map[string]interface{}{"user_id": userID})
res, err := client.Enqueue(t) // This task will be queued in `sync-event`.
```

And if we pass the queue name when enqueue, the default queue name should be overridden. 

```go
// This task will be queued in `another` queue.
res, err := client.Enqueue(t1, asynq.Queue("another"))
```

**Comment by mingrammer** [comment]
If you agree with it, I can work for it.

**Comment by hibiken** [comment]
@mingrammer  Thank you for opening this issue!

Actually, we have [`SetDefaultOptions`](https://pkg.go.dev/github.com/hibiken/asynq#Client.SetDefaultOptions) method on `Client`. Would this work for your use case?

Example:

```go
client := asynq.NewClient(r)
defer client.Close()

// Set default options for "sync:user" tasks.
client.SetDefaultOptions("sync:user", asynq.Queue("sync-event"))

t := asynq.NewTask("sync:user", map[string]interface{}{"user_id": userID})
res,  err := client.Enqueue(t) // t will be enqueued to "sync-event" queue. 
```

**Comment by mingrammer** [comment]
@hibiken Oh, I didn't check that method. Thank you for letting me know it.

But `SetDefaultOptions` seems to apply to each task. How do you think about a feature that supports global default options for all tasks for a client?

**Comment by hibiken** [comment]
Hmm I can see the use case for providing a method to set the global defaults. But I'm hesitant to add yet another method to set defaults.
I'll keep this issue open for now to see if other people want this feature, too.

If this feature request gets a lot of upvotes, I think it validates that this is a common need.

**Comment by hibiken** [comment]
Closing this issue for now. I'll revisit if I get similar feature requests.
