### ISSUE TITLE
[FEATURE REQUEST] Redis key prefix

### ISSUE THREAD

**Issue by hellish** [hibiken/asynq#241]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I want to be able to specify a prefix for all redis keys and pub sub channels used in this library. right now everything resides in asynq.* namespace but with a prefix it will be myapp.asynq.*

**Comment by hibiken** [comment]
@hellish  Thank you for opening this issue!
Would you mind explaining the reason you need this feature in detail, so that I can understand the use case.
It shouldn't be too difficult to add this feature, but I'm not 100% convinced that we need to support this.

**Comment by hibiken** [comment]
Closing this for now. @hellish feel free to reopen the issue if this is still something that you're interested in.

**Comment by zdraganov** [comment]
In detail, you can use the same Redis instance for multiple services that are running asynq. If so, we want to have separate redis entries for each of the service, so we can have `payment_asynq:...` , `order_asynq:...` as any of those will be in the scope of the service itself.

**Comment by hibiken** [comment]
@zdraganov thank you for the comment. 
Can we achieve that with custom queue names? 
For example, you can create payment related queues such as `"payment:foo"`, `"payment:bar"`, etc
and create order related queues such as `"order:baz"`, `"order:qux"`, etc.

**Comment by gurupras** [comment]
One neat way in which a prefix would help is to be able to host multiple isolated asynq-based worker pools within one redis server.
