### ISSUE TITLE
[FEATURE REQUEST] Asynq logo

### ISSUE THREAD

**Issue by koddr** [hibiken/asynq#260]
**Is your feature request related to a problem? Please describe.**
No logo for the project is not a problem, but it affects the growth of the community and the overall recognition of the product. So, I think it's worth taking care of this now.

**Describe the solution you'd like**
Below I have prepared three logo that I personally like the most and convey the essence and meaning of Asynq:

![Screenshot 2021-04-05 at 19 34 44](https://user-images.githubusercontent.com/11155743/113598902-7df4bb80-9646-11eb-8e73-56ca679cdb28.png)

@hibiken please let me know which one you more or less like and why. 
Also, tell me what else you would like to add or remove from them?

**Additional context**
I want to say thank you, because I've been looking for such a simple solution for my Go projects for a long time! Therefore, I'd like to participate in the development and popularization of Asynq with such a modest contribution as a logo at the moment 😉 

> Of course, the logo will be made by me for free and released under a Creative Commons license (but with a link to the author at the bottom of the README), don't worry about that. I've already made logos for many Open Source projects, such as [Fiber](https://github.com/gofiber/fiber), [Starlette](https://github.com/koddr/starlette-logo), [Quart](https://github.com/koddr/quart-logo) and more.

**Comment by hibiken** [comment]
@koddr This is amazing, thank you so much!

I personally like the second one, it looks very clean :) 

Would you mind creating different variations of the second one with different
- font
- color (maybe gradient too?)
- angle (I want to see the second one with the angle of the first one)

Once we agree on the logo, I'd like to use it for [asynqmon](https://github.com/hibiken/asynqmon) (Web UI) in its logo section and favicon. 

If you have more ideas on the logo, please let me know 👍

**Comment by koddr** [comment]
Hi,

I'll post the options here so I don't have to think and move on with other fonts.

![Screenshot 2021-04-07 at 17 37 55](https://user-images.githubusercontent.com/11155743/113884923-10709880-97c8-11eb-98fe-663a91beb425.png)

Other font and idea:

![Screenshot 2021-04-07 at 17 56 00](https://user-images.githubusercontent.com/11155743/113887901-8bd34980-97ca-11eb-826c-470422667f0b.png)

> Once we agree on the logo, I'd like to use it for asynqmon (Web UI) in its logo section and favicon.

Of course, just after using Asynqmon I thought that I should make a logo, because it is really missing in the Web UI 👍

**Comment by koddr** [comment]
Hi,

OK. I'm done with the understanding that it didn't work out to come up with any more distinctive logo. I can certainly send you my attempts, but they are really worse than [this](https://user-images.githubusercontent.com/11155743/113884923-10709880-97c8-11eb-98fe-663a91beb425.png) sketch. It seems to me that in it I fully guessed the mental notes of the project and was able to reflect the associative visual sequence.

Therefore, I propose to take it as a working sample and evolve it, taking it as a basis. 
And, of course, make a README draft with the new logo.

Let me know, what do you think of that idea? 😉

**Comment by hibiken** [comment]
@koddr Thanks for spending time and energy on this 🙏 
I actually really like [this logo](https://user-images.githubusercontent.com/11155743/113884923-10709880-97c8-11eb-98fe-663a91beb425.png) and would really appreciate if you'd let me use it in this repo and in the Web UI.

Feel free to open a PR with the logo in the README. Or you can also send me the image assets via email at ken.hibino7@gmail.com 👍

**Comment by koddr** [comment]
Great news, @hibiken! 

For now, I'll put all the files in my repository [here](https://github.com/koddr/asynq-logo). 
And today or tomorrow I'll make a PR with the new design into this repository.

![asynq_preview_screenshot](https://user-images.githubusercontent.com/11155743/114539150-dc302880-9c5c-11eb-8f4a-5016f83983c8.jpg)

**Comment by koddr** [comment]
@hibiken PR #262 has been created 👍

**Comment by hibiken** [comment]
Hooray 🎉
PR merged! The README looks awesome now! 
Big thank you to @koddr ❤️

**Comment by koddr** [comment]
You're welcome, Ken!

Also, can you please add this GitHub cover to repository settings?

![Asynq Preview (Screenshot)](https://user-images.githubusercontent.com/11155743/114753107-c0fa1180-9d5f-11eb-8276-19dd89d52195.jpg)

I'll update dashboard screen, when new version of Asynqmon (with logo) will be available.
