### ISSUE TITLE
[QUESTION]  Setting Concurrency does not work

### ISSUE THREAD

**Issue by gopkg-dev** [hibiken/asynq#263]
I set Concurrency = 200, and there are less than 10 at work, and my tasks are tens of thousands.

How can I fix it and make it all work.

@hibiken

**Comment by gopkg-dev** [comment]
![image](https://user-images.githubusercontent.com/58848833/115052196-3e648400-9f10-11eb-962f-1c727fd25288.png)
![image](https://user-images.githubusercontent.com/58848833/115052245-4f14fa00-9f10-11eb-85c9-16b8ee3ffb05.png)

**Comment by hibiken** [comment]
@gopkg-dev thanks for opening this issue!

From the screenshot, it seems like your `asynq.Server` is not configured to consume tasks from your **db_process** queue. 
(It seems like you didn't specify the `Queue` option for your server, which means it only reads from the default queue)

You can configure the server to consume task from **db_process** queue like this:

```go
srv := asynq.NewServer(redisConnOpt, asynq.Config{
    Concurrency: 200,
    Queues: map[string]int{
        "db_process": 1,
    },
})
```

For more detail documentation on the Config, please refer to the [godoc](https://pkg.go.dev/github.com/hibiken/asynq#Config).

Let me know if you are still seeing the issue!

**Comment by hibiken** [comment]
@gopkg-dev Did it solve the issue?

**Comment by gopkg-dev** [comment]
Thanks for your reply, it has been solved, the reason is that the performance of redis running in docker is limited.

**Comment by abdeljalil09** [comment]
i have the same issue i set it to 1000 and i only see no more than 10 active workers in asynqmon
