### ISSUE TITLE
[BUG] Task worker process the wrong job

### ISSUE THREAD

**Issue by tyuwan** [hibiken/asynq#266]
**Describe the bug**
Task worker `HandleParseBookTask` process the wrong job when the task type name `parse:book_chapters` is similar to `parse:book`. It will work if both HandleFunc is defined. I was wondering if this is mux related issue?

**To Reproduce**
```go
const (
	TypeParseBook      = "parse:book"
	TypeParseBookChapters = "parse:book_chapters"
)
```
```go
func main() {
	r := asynq.RedisClientOpt{Addr: redisAddr}
	tasks.AsynqClient = asynq.NewClient(r)

        mux := asynq.NewServeMux()
	mux.HandleFunc(tasks.TypeParseBook, tasks.HandleParseBookTask)
        // mux.HandleFunc(tasks.TypeParseBookChapters, tasks.HandleParseBookChaptersTask)
}
```

**Environment (please complete the following information):**
 - OS: MacOS running docker
 - Version of `asynq` package v0.17.1

**Comment by hibiken** [comment]
@tyuwan Thanks for opening this issue!

This is the intended behavior. `ServeMux` matches the type of each task against a list of registered patterns and calls the handler for the pattern that most closely matches the task's type name.  [The doc](https://pkg.go.dev/github.com/hibiken/asynq#ServeMux) describes this behavior.
This enables things like 
- fallback handler ([Example](https://github.com/hibiken/asynq/wiki/Handler-Deep-Dive#using-servemux))
- middleware function applied to group of tasks ([Example](https://github.com/hibiken/asynq/wiki/Handler-Deep-Dive#grouping-middlewares))

Let me know if you have questions on this!
