### ISSUE TITLE
[FEATURE REQUEST] run periodic task once a time

### ISSUE THREAD

**Issue by ChristianYeah** [hibiken/asynq#267]
Hi, I'm wondering if this feature will be included in the future.

for example, one has a heavy load task every 30 minutes. It reads a batch of DB results and then does the calculation, but it could last over 30 minutes or more. In case of dirty read or something, a unique periodic task is required.

currently, I can do some tricks to avoid this circumstance, while it wastes performance

**Comment by hibiken** [comment]
@ChristianYeah Thanks for opening an issue!

Could you describe the feature you want to see if more detail?
From what you shared, it sounds like you are using `Scheduler` to enqueue task periodically (every 30 mins). But the task may take more than 30mins to process. If the previous task hasn't been completed, you don't want to enqueue another task. Is that what you want to see?

**Comment by ChristianYeah** [comment]
> @ChristianYeah Thanks for opening an issue!
> 
> Could you describe the feature you want to see if more detail?
> From what you shared, it sounds like you are using `Scheduler` to enqueue task periodically (every 30 mins). But the task may take more than 30mins to process. If the previous task hasn't been completed, you don't want to enqueue another task. Is that what you want to see?

yes it is. sorry for my poor english.

**Comment by hibiken** [comment]
No worries! I just wanted to see if you can provide more details.

But it sounds like you can just use `Unique` option when enqueueing tasks with `Scheduler`.

Example:
```go
// unique lock will be held by the task for 1h or until the task gets successfully processed.
scheduler.Register("* * * * *", task, asynq.Unique(1 * time.Hour)) 
```

Does this meet your requirement?

**Comment by ChristianYeah** [comment]
> No worries! I just wanted to see if you can provide more details.
> 
> But it sounds like you can just use `Unique` option when enqueueing tasks with `Scheduler`.
> 
> Example:
> 
> ```go
> // unique lock will be held by the task for 1h or until the task gets successfully processed.
> scheduler.Register("* * * * *", task, asynq.Unique(1 * time.Hour)) 
> ```
> 
> Does this meet your requirement?

that helps, thank you
