### ISSUE TITLE
[FEATURE REQUEST] Expose raw data of payload

### ISSUE THREAD

**Issue by kamatama41** [hibiken/asynq#269]
**Is your feature request related to a problem? Please describe.**
Encoding / decoding task parameters is too much to write especially when task has many parameters, so I'd like to convert task parameters into a struct via another library (assuming [mitchellh/mapstructure](https://github.com/mitchellh/mapstructure)). In order to do that, I need the raw data of Payload when decoding params.

**example**
```go
type TaskParameter struct {
	Param1 int
	Param2 string
}

var client *asynq.Client

func EnqueueTask(param TaskParameter) error {
	payload := map[string]interface{}{}
	if err := mapstructure.Decode(param, &payload); err != nil {
		return err
	}
	if _, err := client.Enqueue(asynq.NewTask("task", payload)); err != nil {
		return err
	}
	return nil
}

func ExecuteTask(ctx context.Context, task *asynq.Task) error {
	var data map[string]interface{} = task.Payload.Data() // I need this

	var param TaskParameter
	if err := mapstructure.Decode(data, &param); err != nil {
		return err
	}

	// Process the task
	// ...
	return nil
}
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hibiken** [comment]
@kamatama41, thank you for opening this issue!

I'm actually updating the API in the next version: 
New API takes arbitrary array of bytes as payload.
```go
func NewTask(tasktype string, payload []byte) *Task

// Type returns the task type.
func (t *Task) Type() string 

// Payload returns the payload data.
func (t *Task) Payload() []byte
```

What this means is that you can write code like this:

```go
func EnqueueTask(param TaskParameter) error {
        // You can serialize your data however you want, it doesn't need to be JSON.
	b, err := json.Marshal(param)
        if err != nil {
		return err
	}
	_, err := client.Enqueue(asynq.NewTask("task", b))
        return err
}

func ExecuteTask(ctx context.Context, task *asynq.Task) error {
        var params TaskParameter 
        if err := json.Unmarshal(task.Payload(), &params); err != nil {
              return err
        }
        //  Process the task ...
}
```

I'm actively working on the feature, and should be able to release it in a few more weeks 👍

**Comment by kamatama41** [comment]
Got it, I'm looking forward to that 😃
