### ISSUE TITLE
[QUESTION] How does priority queue work?

### ISSUE THREAD

**Issue by sujit-baniya** [hibiken/asynq#271]
Please suggest how the priority queue works in following scenario:

```go
srv := asynq.NewServer(redis, asynq.Config{
    Concurrency: 10,
    Queues: map[string]int{
        "critical": 6,
        "default":  3,
        "low":      1,
    },
})
```

There are already 1K messages on `low`, When I send a message on `critical` while other messages are still enqueued, will this message consume at first or wait for first 1K  to get completed?

I'm trying to understand how priority queue works

**Comment by hibiken** [comment]
@sujit-baniya thank you for asking!

It's documented here in godoc (https://pkg.go.dev/github.com/hibiken/asynq#Config). Please take a look at `Queues` and `StrictPriority` fields. Also, there's a wiki page explaining how queue priorities work: https://github.com/hibiken/asynq/wiki/Queue-Priority

Let me know if it's still unclear! That means the documentation can be improved.

**Comment by hibiken** [comment]
Once a task is in pending state, it's appending to a list in redis. This list has FIFO semantics.
If a task is scheduled to be processed in the future (via `ProcessIn` or `ProcessAt` option), the task is stored in a sorted-set in redis (score being the unix time of the process_at time). 
Asynq internally manages these tasks state and move tasks from sorted-set to the list mentioned above.

If you are interested in the redis key design, good place to start is base.go and rdb.go file.

**Comment by hibiken** [comment]
Closing this issue.
