### ISSUE TITLE
Cleanup active tasks when restarting the server

### ISSUE THREAD

**Issue by xn3cr0nx** [hibiken/asynq#277]
Hello there :wave: 

Thanks for your great work! I have a question about a mechanism I would like to implement, but I don't understand whether it is feasible.

I have some events that are scheduled once. The event includes a `starting_at` property, hence when a new event is created I enqueue a new task that basically waits for `starting_at`. When `starting_at` is reached, I enqueue a new task to process the event.

The process mechanism or the tasks chain is not important for the question. If while the first task is waiting for `starting_at` I gracefully stop my service, `asynq` keeps the event in active state. When I restart the service, I want to dispatch the first task again in order to wait for the event to be process, but what I end up with is two active tasks. The first active task (the one that I expect would have been interrupted), is processed again later when the second active task is over (I'm not sure why, it is not retried because it is not in retry state).

Is it feasible to cleanup active tasks when the service is restarted in order to avoid active tasks conflicts/retries and be sure about my service state?

**Comment by crossworth** [comment]
Hi, I dont know if I understood your problem, but couldn't you use `ProcessAt` and avoid removing and handling the waiting for `starting_at`?

https://github.com/hibiken/asynq/wiki/Getting-Started#client-program
https://pkg.go.dev/github.com/hibiken/asynq?utm_source=godoc#ProcessAt

You could try cancel the active task as well, but you will have to know the task id.
https://github.com/hibiken/asynq/blob/2516c4babac835a04b59822eebb9a0016351e177/inspeq/inspector.go#L679-L685

**Comment by xn3cr0nx** [comment]
Hi @crossworth, thanks for your feedback! 

Yes, using `ProcessAt` is for sure smarter and more elegant than having a counter, so I will employ it, but I guess the general issue persists. In the event the service crashes, when it restarts how can I check if the event was correctly scheduled before the crash in order to decide if to schedule it on startup or not?

It looks like I have to keep track of scheduled tasks through inspector as well, in order to be sure tasks are scheduled as expected. I didn't consider to use Inspector, but now that I look at its api it looks feasible to me. Thanks for you help

**Comment by hibiken** [comment]
@xn3cr0nx Thank you for creating an issue, and @crossworth thank you so much for responding quickly 🎉 

I believe using the `ProcessAt` and `Unique` options satisfy your requirements? Let me know if you are still having trouble. Otherwise, is it okay to close this issue?

**Comment by xn3cr0nx** [comment]
Thanks @hibiken, `ProcessAt` and `Unique` worked perfectly for me. Closing the issue!
