### ISSUE TITLE
[BUG] Enqueue message from NodeJS

### ISSUE THREAD

**Issue by acgfbr** [hibiken/asynq#278]
**Describe the bug**
My system enqueue all of messages in nodejs, just route to micro service enqueuer, example:
i have multi queue system in sqs, php and im trying to rollout all of this systems to go, but i want to enqueue in node to sqs and golang 

I'm queuing a payload from nodejs and asynq can't remove the message

**To Reproduce**
Steps to reproduce the behavior (Code snippets if applicable):

NodeJS code
![image](https://user-images.githubusercontent.com/8755427/121115061-04ff1500-c7eb-11eb-9806-9785993950d9.png)

Payload in redis by NodeJS
Payload in redis by Golang asynq enqueue

![image](https://user-images.githubusercontent.com/8755427/121115142-2bbd4b80-c7eb-11eb-863c-49f5a4f9d27b.png)

The golang message enqueued by go proccess normally, nodejs message not removed from queue
![image](https://user-images.githubusercontent.com/8755427/121115183-38da3a80-c7eb-11eb-90ce-a7ff994b29d1.png)

Message stuck:
![image](https://user-images.githubusercontent.com/8755427/121115454-79d24f00-c7eb-11eb-8e9b-fecc71da7a8b.png)

The payload as 100% matching, what can i be doing wrong?
Can u help me ?

My go code from server:
![image](https://user-images.githubusercontent.com/8755427/121115831-f8c78780-c7eb-11eb-8a29-8c091f3e2683.png)

Job:
![image](https://user-images.githubusercontent.com/8755427/121115848-00872c00-c7ec-11eb-8a0f-950a16b91296.png)

**Comment by crossworth** [comment]
Hi, maybe this is related to this: https://github.com/hibiken/asynq/issues/109#issuecomment-796809596

Which should be fixed when the API uses a byte slice as payload (https://github.com/hibiken/asynq/pull/253).

**Comment by acgfbr** [comment]
Oh great, i change the order of json and now working, thanks man!
![image](https://user-images.githubusercontent.com/8755427/121117387-6eccee00-c7ee-11eb-8eec-7c775d0130c7.png)
