### ISSUE TITLE
[QUESTION] Get Queue and Task Information in Queue Handler

### ISSUE THREAD

**Issue by sujit-baniya** [hibiken/asynq#281]
In case of using same handler for different queues, is it possible to get the current queue and task information in the handler? If yes, how?

**Comment by hibiken** [comment]
You can get that information from the context, use the following function to extract the data from the context:
- [GetQueueName](https://pkg.go.dev/github.com/hibiken/asynq#GetMaxRetry)
- [GetTaskID](https://pkg.go.dev/github.com/hibiken/asynq#GetMaxRetry)
- [GetMaxRetry](https://pkg.go.dev/github.com/hibiken/asynq#GetMaxRetry)
- [GetRetryCount](https://pkg.go.dev/github.com/hibiken/asynq#GetMaxRetry)

Example:
```go
func myHandler(ctx context, task *asynq.Task) error {
    qname, ok := asynq.GetQueueName(ctx)
    if !ok {
        log.Printf("Could not retrieve queue name from the context")
        qname = "unknown"
    }
   // use qname
}
```
