### ISSUE TITLE
[FEATURE REQUEST] Use interfaces

### ISSUE THREAD

**Issue by mrsufgi** [hibiken/asynq#282]
**Is your feature request related to a problem? Please describe.**
Im using asynq in several projects and I find myself create partial interfaces for asynq.Client (type) so I can mock on my unit tests. It's tedius, partial and redunant and could be helpful to have "Official" interfaces returned from NewClient function

further reference on how do you mock uninterfaced dependencies
https://dev.to/jonfriesen/mocking-dependencies-in-go-1h4d

**Describe the solution you'd like**
client.go -> callings `NewClient` returns `AsynqClient` interface instead of Client type (struct)

Thanks for this awesome package! <3

**Comment by crossworth** [comment]
Hi, I don't think we improve the library by doing this. The idiomatic way is for the consumer to define the interface, the reference that you pointed show that as well, I know that is a bit tedius doing that for every project, but you could use a interface generator tool or create a wrapper around the AsyncClient.

For more references see the links below:

- https://github.com/golang/go/wiki/CodeReviewComments#interfaces
- https://www.ardanlabs.com/blog/2016/10/avoid-interface-pollution.html
- https://rakyll.org/interface-pollution/

There is a video where William Kennedy talks exactly about this scenario, but I couldn't find it.

Anyway, that's my opinion.

**Comment by hibiken** [comment]
@mrsufgi Thank you for opening this issue! While I can related to the pain of defining interface in every project, I agree with @crossworth in that we shouldn't make this API change. 

These feedback on APIs are very useful, so if you have more please don't hesitate to open an issue!

**Comment by mrsufgi** [comment]
Thank you for your answers! I agree, if interfaces are only meant for testing, I can use something like 
https://github.com/vburenin/ifacemaker

To easily generate them from structs :) 
🥳
