### ISSUE TITLE
Ability to get the status of a task by id

### ISSUE THREAD

**Issue by Harrison-Miller** [hibiken/asynq#284]
**Is your feature request related to a problem? Please describe.**
Currently when using the inspector to find the status of a task you need to loop through every task of each status type. Which is really inconvenient.

```
ListPendingTasks...
ListActiveTasks...
ListScheduledTasks...
ListArchivedTasks...
```

**Describe the solution you'd like**
I would like to be able to get the task status and metadata using inspector.
`GetTaskByID`

**Comment by crossworth** [comment]
Hi, looks like that in the next version we will have: `GetTaskInfo(qname, id string) (*TaskInfo, error)`.

Commit: https://github.com/hibiken/asynq/commit/26d035e0506c7a11ed0212f911ab785b3998bc6c

**Comment by Harrison-Miller** [comment]
Perfect, I also appreciate the consolidation of the different task types into a single struct.
