### ISSUE TITLE
Multiple asynq servers serve different queues

### ISSUE THREAD

**Issue by jiangdi0924** [hibiken/asynq#290]
Hi hibiken,  Nice repo, it is very useful to me , thank you!

In find the issue   [issues/213](https://github.com/hibiken/asynq/issues/213)  about muti server feature.
Can you explain how to define and use it ?

**Comment by hibiken** [comment]
@jiangdi0924 thank you for opening an issue. Looks like you got an answer in the other issue? Let me know if you have more questions. I'm on vacation currently and may be slow to respond 😬

**Comment by jiangdi0924** [comment]
> @jiangdi0924 thank you for opening an issue. Looks like you got an answer in the other issue? Let me know if you have more questions. I'm on vacation currently and may be slow to respond 😬

Yea, i find the solution. Happy vacation !😎,  closed
