### ISSUE TITLE
[BUG] message always pending

### ISSUE THREAD

**Issue by moulo1982** [hibiken/asynq#292]
**Describe the bug**
message always pending

**To Reproduce**
Steps to reproduce the behavior (Code snippets if applicable):
Queue Name is “CamelCase”，Enqueue method use QueueOpting （ 

// Queue name is case-insensitive and the lowercased version is used.
func Queue(qname string) Option {
	return queueOption(strings.ToLower(qname))
}

）， but Server “asynq.Config”‘s Queues not “ToLower”。so， message always pending。

Sorry， My English is very pool。

**Comment by hibiken** [comment]
@moulo1982 Thank you so much for spotting this bug!

Now that I'm thinking about this, I think it doesn't make much sense to make queue names case-insensitive?
Do you think we should just use the queue name provided as is (without normalize it to lowercase)?

What do you think? /cc @crossworth

**Comment by crossworth** [comment]
I think we can use as provided, I don't see any problem with it, simple is better.

**Comment by moulo1982** [comment]
> I think we can use as provided, I don't see any problem with it, simple is better.

I think it's good
