### ISSUE TITLE
[FEATURE REQUEST] Upgrade go-redis dependency to v8

### ISSUE THREAD

**Issue by strobus** [hibiken/asynq#293]
**Is your feature request related to a problem? Please describe.**
I'm ready to upgrade my projects to go-redis/v8 but asynq is holding me back. I'd rather not have 2 versions of go-redis in my stack. Are there plans to upgrade?

**Describe the solution you'd like**
Upgrade Asynq to go-redis/v8

**Describe alternatives you've considered**
N/A

**Additional context**
go-redis/v8 has been out of beta for a while.

**Comment by hibiken** [comment]
@strobus Thanks for opening this issue!

Yes, I've been meaning to update to v8. I just haven't had a chance to do that yet since it was not a high priority.
I'll probably get to it within the coming week or so, but if this is urgent for you, please feel free to open a PR 👍
