### ISSUE TITLE
[BUG] the example demo do not work well

### ISSUE THREAD

**Issue by wsqyouth** [hibiken/asynq#295]
**Describe the bug**
the exampe demo of the project is not working well, the beginner must study the grammer and try to  fix it 
may you can fix it

**Comment by wsqyouth** [comment]
mp proj:
 https://github.com/wsqyouth/coopers_go_code/tree/master/asynq

**Comment by hibiken** [comment]
Thanks for reporting! Fixed build errors.
Let me know if I missed anything in #296 👍
