### ISSUE TITLE
[FEATURE REQUEST] empty taskname should not be publish

### ISSUE THREAD

**Issue by victor-wzq** [hibiken/asynq#297]
i push a task with empty taskname,
but i can't comsume this task,
i think function Enqueue should check taskname

**Comment by hibiken** [comment]
@victor-wzq thank you for creating this issue! I haven't thought about this edge case so thank you for pointing this out  👍 

I think we have a couple of options:
1. `NewTask` function can panic given a empty typename 
2. `Enqueue` function can return an error if the task has an empty typename
3.  Allow tasks to have an empty typename

Let me know what you think! /cc @crossworth

**Comment by crossworth** [comment]
I think we should go with option 2.

1. We should avoid panic's, we dont know where the typename could came from (maybe user input or dynamic generated) and panicing makes it harder to the caller to handle it, we should avoid panic as much as possible as a library. By returning an error we can effectively tell the caller what went wrong.

2. I think is the best option, Enqueue already returns errors like `ErrDuplicateTask`, it would be easy to handle.

3. I dont think its a good option, can cause a lot of confusion, makes debuging harder and most of the times the task should have a typename.

**Comment by crossworth** [comment]
@hibiken this can be closed.

**Comment by hibiken** [comment]
Closing this. Thank you @Luqqk!
