### ISSUE TITLE
Question: is it possible for multiple "servers" to "forward" the same messages

### ISSUE THREAD

**Issue by seanyu4296** [hibiken/asynq#300]
Hi, @hibiken 

First off, awesome lib! I'm trying to study and use your library. I'm pretty new to go and redis too. 

So, Can I ask is it possible for multiple "servers" to "forward" the same messages given the code below?

```golang
var forwardCmd = redis.NewScript(`
local ids = redis.call("ZRANGEBYSCORE", KEYS[1], "-inf", ARGV[1], "LIMIT", 0, 100)
for _, id in ipairs(ids) do
	redis.call("LPUSH", KEYS[2], id)
	redis.call("ZREM", KEYS[1], id)
	redis.call("HSET", ARGV[2] .. id, "state", "pending")
end
return table.getn(ids)`)
```

wouldn't 2 servers querying from the same queues end up querying the same items if they are started almost at the same time? 
Wondering also if you have some docs explaining the rough architecture of your lib, it will be tremendously helpful

Thanks,

**Comment by hibiken** [comment]
Hi @seanyu4296 thank you for the question!

Redis is single-threaded from the POV of commands execution.
Please take a look at this [Atomicity of scripts](https://redis.io/commands/eval#atomicity-of-scripts) in redis doc.

quotes from redis documentation:
> Redis uses the same Lua interpreter to run all the commands. Also Redis guarantees that a script is executed in an atomic way: no other script or Redis command will be executed while a script is being executed. This semantic is similar to the one of MULTI / EXEC. From the point of view of all the other clients the effects of a script are either still not visible or already completed.
> However this also means that executing slow scripts is not a good idea. It is not hard to create fast scripts, as the script overhead is very low, but if you are going to use slow scripts you should be aware that while the script is running no other client can execute commands.

Second part about slow scripts explains why we are currently dealing with 100 tasks at a time (to avoid running a slow script which blocks other commands from executing).

I'll document the design once the library is stable (i.e. version 1.0 release).

**Comment by seanyu4296** [comment]
gotcha thanks for the quick, succinct, and clear explanation! @hibiken 

Do you have a timeline or roadmap to version 1.0 release? 😄

**Comment by hibiken** [comment]
I have this milestone https://github.com/hibiken/asynq/milestone/2 

The roadmap is not set in stone, it may change in the future.

**Comment by seanyu4296** [comment]
Awesome stuff thanks! @hibiken
