### ISSUE TITLE
[FEATURE REQUEST] Adding a small amount of task information to asyncq.Task

### ISSUE THREAD

**Issue by zhaolion** [hibiken/asynq#304]
**Is your feature request related to a problem? Please describe.**

My feature: I need to know the number of retries to update the database related information. Currently the processor cannot get information about the number of retries related to the task

**Describe the solution you'd like**

```
func (processor *ImageProcessor) ProcessTask(ctx context.Context, t *asynq.Task) error {
	log.Printf("Retries: %d", t.Retries())
	return nil
}
```

** Additional context
This is a very marginal feature, and I rarely encounter it. If it is too difficult to do it, you can consider close this issue or consider to implement this feature in the next major version.

**Comment by crossworth** [comment]
Hello @zhaolion.

You can use `func GetRetryCount(ctx context.Context) (n int, ok bool)` to get the retry count from the context.
https://pkg.go.dev/github.com/hibiken/asynq?utm_source=godoc#GetRetryCount

**Comment by zhaolion** [comment]
> Hello @zhaolion.
> 
> You can use `func GetRetryCount(ctx context.Context) (n int, ok bool)` to get the retry count from the context.
> https://pkg.go.dev/github.com/hibiken/asynq?utm_source=godoc#GetRetryCount

cool, thanks for your comment
