### ISSUE TITLE
Error when upgrading from 0.17 to 0.18

### ISSUE THREAD

**Issue by sicko7947** [hibiken/asynq#305]
**Describe the bug**

_2021/08/03 16:40:48 INTERNAL_ERROR: redis eval error: ERR Error running script (call to f_a3d9ea12b22222adbcad90882a9e57f1874e165a): @user_script:2: @user_script: 2: Wrong number of args calling Redis command From Lua script_

**To Reproduce**
Enqueue tasks
![image](https://user-images.githubusercontent.com/19926182/127969850-a34288ec-459a-4a51-85ed-6f6be5af0cee.png)

**Expected behavior**
On enqueuing the tasks this happens

**Environment (please complete the following information):**
 - OS: Windows 10 x64
 - Version of `asynq` package v0.18.2

**Additional context**
I was using v0.17.1, until today I decided to update the package and tryout some new features and then this bug came out saying Lua script args number incorrect.

**Comment by hibiken** [comment]
@sicko7947 thank you for opening an issue!

I have written a upgrade guide from 0.17 to 0.18. Please take a look at https://github.com/hibiken/asynq/wiki/Version-Upgrade-Guide-(from-0.17-to-0.18), and let me know if you have any questions.

**Comment by hibiken** [comment]
Closing this.
