### ISSUE TITLE
I can’t view the specific status of the task operation these days. What is the reason?

### ISSUE THREAD

**Issue by LINJINTIANDE** [hibiken/asynq#311]
I can’t view the specific status of the task operation these days. What is the reason?
As long as there is running in the queue, you cannot see the data running redis
![image](https://user-images.githubusercontent.com/42436479/129318089-db2711a3-8413-4370-9868-31e878c2d6fb.png)
![image](https://user-images.githubusercontent.com/42436479/129322427-762dbe17-32f1-4875-be93-bc59cb224f11.png)

**Comment by hibiken** [comment]
Hi @LINJINTIANDE, thank you for opening this issue.

Which version of asynq package and asynqmon are you using?
This may be version compatibility issue.

**Comment by LINJINTIANDE** [comment]
ansyq v0.17.1 ，asynqmon is the latest version

**Comment by LINJINTIANDE** [comment]
Upgrade asynq v0.18.3, check the queue details, the following error occurred
![image](https://user-images.githubusercontent.com/42436479/129449043-31c267b1-8091-41bd-9ced-ce15a1a089a3.png)
![image](https://user-images.githubusercontent.com/42436479/129449053-21e1f80a-154d-40a1-933d-212e02a3eaa7.png)

**Comment by hibiken** [comment]
I see. This has come up a number of times; asynq 0.17.x is compatible with asynqmon 0.1.x.
(If you are using docker, I'd suggest you pin the version number of the image).

When you upgrade from asynq 0.17 to 0.18, did you follow the guide at https://github.com/hibiken/asynq/wiki/Version-Upgrade-Guide-(from-0.17-to-0.18)?

**Comment by LINJINTIANDE** [comment]
Upgrade to asynq v0.18.3 is normal, thank you for your reply
