### ISSUE TITLE
[FEATURE REQUEST] Provide the task ID to the task object when using the handler callback.

### ISSUE THREAD

**Issue by pbarnum** [hibiken/asynq#315]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to get the ID of the task currently being processed in the handler's callback function.

**Describe alternatives you've considered**
Adding our own ID to the task object and getting it through the payload.

**Additional context**
I would like to reference the resource (task) generated for logging purposes. Currently, the `Task` interface only exposes `Type() string` and `Payload() []byte`.

**Comment by crossworth** [comment]
Does [`GetTaskID`](https://pkg.go.dev/github.com/hibiken/asynq?utm_source=godoc#GetTaskID) solves your problem?

```go
func HandleEmailDeliveryTask(ctx context.Context, t *asynq.Task) error {
    id, ok := GetTaskID(ctx)
    return nil
}
```

**Comment by pbarnum** [comment]
Oh gosh yes it does! I don't know how I missed that. Thank you 👍
