### ISSUE TITLE
[FEATURE REQUEST] callback for archived tasks

### ISSUE THREAD

**Issue by AlexeyBelezeko** [hibiken/asynq#327]
Right now asynq doesn't provide the functionality to notify go code about archived tasks. For example, I have a task for uploading images from one server to another. In case of failure, I want to retry this operation a few times and if the problem didn't fix I want to create a ticket or fire an alert. 

I suggest adding some call back for archiving tasks to asynq server configuration.

**Comment by hibiken** [comment]
@AlexeyBelezeko Thank you for opening this issue!

I think this is a common need and we do have a hook [`ErrorHandler`](https://pkg.go.dev/github.com/hibiken/asynq#Config.ErrorHandler) which gets invoked every time `Handler.ProcessTask` returns a non-nil error. We can use this hook to trigger alerts when task has reached its max-retry.

```go
func handleTaskError(ctx context.Context, task *asynq.Task, err error) {
     // Note: Skip checking `ok` since we are sure that this context has these values.
     retried, _ := asynq.GetRetryCount(ctx)
     maxRetry, _ := asynq.GetMaxRetry(ctx)
     if retried >= maxRetry {
           // Task will be archived, trigger an alert
     }
     // handle errors (e.g. report error to error reporting service)
}

// ...

srv := asynq.NewServer(redisConnOpt, asynq.Config{
     ErrorHandler: asynqErrorHandlerFunc(handleTaskError),
     // ... other config options 
})
``` 

Let me know if this works!

**Comment by AlexeyBelezeko** [comment]
@hibiken thank you for your answer. But this hook will be triggered every time when the task will be retried. I ask about hook which will be called only once when the task achieved max retries or deadline.

**Comment by AlexeyBelezeko** [comment]
@hibiken thank you for a quick answer. This is exactly what I've been looking for. Sorry for my blindness I found out that the same snippet contains in the ErrorHandler comment section.

**Comment by hibiken** [comment]
Glad I could help!

No worries. I appreciate these issues because it's a signal that I can do a better job in documentation.
