### ISSUE TITLE
[QUESTION] Does Asynq support multiple servers and processes? Is there a locking mechanism?

### ISSUE THREAD

**Issue by zhaitailang** [hibiken/asynq#332]

**Comment by hibiken** [comment]
@zhaitailang thank you for the question.
Yes, you can run multiple server processes to read from the same queues. For the most part, no locks are needed since we execute Lua script on Redis which is atomic in terms of execution of the script (see https://redis.io/commands/eval#atomicity-of-scripts).

**Comment by gschurck** [comment]
I am wondering, in that case how Redis decides which server to choose to send the task to ?

**Comment by gschurck** [comment]
@hibiken I am wondering, in that case how Redis decides which server to choose to send the task to ?

**Comment by kenshin579** [comment]
I'm developing a server program to allow distributed scheduling across multiple servers, and currently, I'm considering the asynq library. I'm a bit unclear on whether I can run multiple periodic schedulers as multiple instances.

- In my program, I need to guaranteed at least one execution of a task even if there is more than one server instance is running

In your answer to this issue, you said that it's okay to run on multiple servers without locking. But, in the wiki doc mentioned below, it seems like I have to run only one periodic scheduler which means I cannot run my program in multiple servers. 

Should I just make sure that only one instance is running the periodic scheduler? Is my understanding correct?

> "You have to ensure only a single scheduler is running for a schedule at a time, otherwise you’d end up with duplicate tasks. Using a centralized approach means the schedule doesn’t have to be synchronized, and the service can operate without using locks."

Reference: https://github.com/hibiken/asynq/wiki/Periodic-Tasks
