### ISSUE TITLE
[FEATURE REQUEST] The time in non crontab format is 2021-11-08 02:00:00. Does asynq support it

### ISSUE THREAD

**Issue by zijiwork** [hibiken/asynq#347]
Do you support one-time tasks? Use non crontab format 2021-11-08 02:00:00. Does asynq support it

**Comment by hibiken** [comment]
@zijiwork Thank you for opening an issue!
We do have `ProcessAt` option to specify when the task should get picked up by a worker?

Could you describe your use case in more detail? I want to make sure if this library is a good choice for your use case :)

**Comment by zijiwork** [comment]
Thank you 'processat' for fixing my problem ，asynq is a good project

**Comment by zijiwork** [comment]
> @zijiwork Thank you for opening an issue! We do have `ProcessAt` option to specify when the task should get picked up by a worker.
> 
> Could you describe your use case in more detail? I want to make sure if this library is a good choice for your use case :)

Thank you 'processat' for fixing my problem ，asynq is a good project
