### ISSUE TITLE
[FEATURE REQUEST] retry policy enhancement

### ISSUE THREAD

**Issue by sersh88** [hibiken/asynq#363]
Feature request about retry policy. 
Sometimes, when doing a task, it is clear that it will not be possible to complete it even on subsequent attempts. 
So, it will be useful for a task handler to return special error type after which the task will be completely failed and no retries will be processed.
Also another enhancement is to be able to modify task payload in task handler. It's useful in some batch tasks, if I need to process i.e. 100 files and succeffully processed 99 of them, 1 was failed due to temporary network problem, so will be great if on next retry attempt task handler could use modifed payload with only 1 item to process.

**Comment by crossworth** [comment]
Hello, you can already handle the error in different ways, see:
https://github.com/hibiken/asynq/wiki/Task-Retry#skip-retry

About changing the task payload, I don't is possible right now, but you can get the same result by enqueuing a new task with the payload changed and returning a skip retry on the task.

**Comment by sersh88** [comment]
Thanks, somehow I missed this SkipRetry error.

**Comment by hibiken** [comment]
@sersh88 thank you for creating this issue and thank you @crossworth for jumping in!

For the first question, please see @crossworth's comment above.

For the second question, payload should be immutable IMO. We introduced task `Result` in v0.19. you could probably write your partial result and read the result in the subsequent attempts.

Example:
```go
func MyHandler(ctx context.Context, task *asynq.Task) error {
    // Read previous result: GetResult function is not available right now, but we can implement if needed.
    prevRes := asynq.GetResult(ctx) 
    res, err := DoStuff(ctx, task, prevResult)
    if err != nil {
        // Write partial result
        if _, err := task.ResultWriter().Write(res); err != nil {
           return fmt.Errorf("failed to write partial result: %v", err)
        }
        return err
    }
    if _, err := task.ResultWriter().Write(res); err != nil {
        return fmt.Errorf("failed to write result: %v", err)
    }
    return nil
}
```
