### ISSUE TITLE
[QUESTION] How to fix duplicate scheduler task in 2 servers?

### ISSUE THREAD

**Issue by xdorro** [hibiken/asynq#371]
Sorry my english is not good,
I am having 1 task scheduled every 15 seconds, its task is to send a notification to the user.
when i deploy it on 2 different servers my users get the same 2 messages, i checked on asynq and see 2 scheduled tasks running side by side. Can you help me fix this?

**Comment by hibiken** [comment]
@xdorro thank you for opening an issue!

Would you mind providing more details? Code snippets would be very helpful.

**Comment by hibiken** [comment]
Any updates? I'm closing this for now, but feel free to re-open if you are still seeing the issue.

**Comment by jinsuojinsuo** [comment]
Same problem
