### ISSUE TITLE
redis eval error

### ISSUE THREAD

**Issue by ruziyi** [hibiken/asynq#380]
**Describe the bug**
I got the error "could not enqueue task: UNKNOWN: redis eval error: ERR Error running script (call to f_6b2833bade2cce3e7bae2440c9187cd23e3ae042): @user_script:5: @user_script: 5: Wrong number of args calling Redis command From Lua script 
" when I try run the code in the docs .

**To Reproduce**
Steps to reproduce the behavior (Code snippets if applicable):
1. Setup background processing ...
2. Enqueue tasks ...
3. See Error ...

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. MacOS, Linux]
 - Version of `asynq` package [e.g. v1.0.0]

**Additional context**

**Comment by ruziyi** [comment]
There may be a problem with the redis version.

**Comment by sersh88** [comment]
I have the same problem. Did you solved it?

**Comment by hibiken** [comment]
@sersh88 it's most likely that the version of redis is below v4.

**Comment by sersh88** [comment]
> @sersh88 it's most likely that the version of redis is below v4.

I have version 5.0.14 and looks like a bit another error:
`UNKNOWN: UNKNOWN: redis eval error: ERR Error running script (call to f_7574d838a4ddc18d626139a5521903c904f1404a): @user_script:30: user_script:30: attempt to perform arithmetic on local 'bytes' (a boolean value)`

Looks like this error may happen becouse of maxmemory setting on redis and `maxmemory-policy allkeys-lru`. Will try to setup additional redis instance just for asynq for unlimited memory policy.

**Comment by hibiken** [comment]
@sersh88 thank you for the update. Feel free to open a issue if that doesn't help 👍

**Comment by jerroldgao** [comment]
> maxmemory

We met the same issue, wondered how do you determine it is because of max memory policy?

**Comment by jerroldgao** [comment]
In our case, there is orphan task left in archive queue, it can't be removed, and being scanned by ZRANGE, but ` Memory Usage ` failed
