### ISSUE TITLE
[FEATURE REQUEST] Backed Support In Memory or Embedded Database

### ISSUE THREAD

**Issue by lucy9x** [hibiken/asynq#382]
Currently asynq only supports redis for backed. It would be great if asynq support in memory or embedded database like SQLite, BadgerDB, BoltDB... for backed

**Comment by hibiken** [comment]
Duplicate of #173

**Comment by ixugo** [comment]
try it [github.com/ixugo/nsqite](https://github.com/ixugo/nsqite) ，support memory，Use gorm to support database transactions
