### ISSUE TITLE
[BUG]  go get github.com/hibiken/asynq/tools/asynq error

### ISSUE THREAD

**Issue by duzhipeng** [hibiken/asynq#388]
**Describe the bug**
go get github.com/hibiken/asynq/tools/asynq error

**To Reproduce**
Steps to reproduce the behavior (Code snippets if applicable):
1. `go get github.com/hibiken/asynq/tools/asynq` or `go get -u github.com/hibiken/asynq/tools/asynq` .
2. The error is shown in the figure below.
3. Installation failed.

**Expected behavior**
The installation is successful without error.

**Screenshots**
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/3648161/151305127-29945104-8f97-4e9a-8915-43ed934028b9.png">

**Environment (please complete the following information):**
 - OS:  MacOS
 - Version of `asynq` package v0.21.0

**Comment by hibiken** [comment]
@duzhipeng Thank you for reporting this. I confirmed the bug on my machine as well. 

Let me look into this in the next few days. In the meantime, please work around this by building the CLI from the source 🙏

**Comment by hibiken** [comment]
This should be fixed now. 

Please feel free to reopen the issue if you see an error when running 

```sh
$ go get github.com/hibiken/asynq/tools/asynq

$ go install github.com/hibiken/asynq/tools/asynq
```
