### ISSUE TITLE
[FEATURE REQUEST] I wan to know this data 'asynq:schedulers:{******} ' how to use

### ISSUE THREAD

**Issue by carrymec** [hibiken/asynq#405]
What is the role of 'asynq:schedulers:{******} ' 
can i delete list in 'asynq:schedulers:{******}'?

**Comment by hibiken** [comment]
We store information about running `Scheduler's` entries in redis for tooling.
In web UI, you can see these entries info in the "Schedulers" page.
In CLI, you can see it when you run `asynq cron ls` command.

Let me know if you have more questions.
