### ISSUE TITLE
[QUESTION] how to delete a delay task

### ISSUE THREAD

**Issue by hzylyq** [hibiken/asynq#414]
```
payload, err := json.Marshal(source)
if err != nil {
	return err
}
task := asynq.NewTask(queueName, payload, options...)

taskInfo, err := c.client.Enqueue(task, options...)

```
how delete task

**Comment by lvsoso** [comment]
use this API to delete or cancel ?

https://github.com/hibiken/asynq/blob/master/inspector.go#L508

**Comment by lvsoso** [comment]
> ```
> payload, err := json.Marshal(source)
> if err != nil {
> 	return err
> }
> task := asynq.NewTask(queueName, payload, options...)
> 
> taskInfo, err := c.client.Enqueue(task, options...)
> ```
> 
> how delete task

use this API to delete or cancel ?

https://github.com/hibiken/asynq/blob/master/inspector.go#L508

**Comment by hibiken** [comment]
@hzylyq Thanks for opening an issue!

The API suggested by @lvsoso should do what you want 👍 

Note: [`Inspector.DeleteTask`](https://pkg.go.dev/github.com/hibiken/asynq#Inspector.DeleteTask) applies to non-active tasks, if you need to cancel an active task, please use [`Inspector.CancelProcessing`](https://pkg.go.dev/github.com/hibiken/asynq#Inspector.CancelProcessing) instead.
