### ISSUE TITLE
how to chain a set of tasks to be executed one by one?

### ISSUE THREAD

**Issue by micross** [hibiken/asynq#419]

**Comment by hibiken** [comment]
@micross Thank you for the question! 
I'm planning to work on [a feature ](https://github.com/hibiken/asynq/issues/244) which would enable user to define a chain of tasks and run it as a workflow. This feature is a large feature and I'm still in the design phase and most likely start working on it in a few months.

In the meantime, you'll have to use a different approach. A common way to deal with this is to enqueue a taskA which would enqueue another taskB and so on. Let me know if you have any questions!

**Comment by hibiken** [comment]
Closing this, Feel free to reopen if you have follow-up questions :)
