### ISSUE TITLE
Multiple handlers for a specific task type ?

### ISSUE THREAD

**Issue by raynaudoe** [hibiken/asynq#421]
Let's say that I have a task named `data:process` and the payload contains some raw json for example and I want that task to be distributed to 'several' handlers, the task should be processed by 'all' the handlers. 
Something like:

```go
 mux := asynq.NewServeMux()
 mux.HandleFunc("data:process", dataProcessorA)
 mux.HandleFunc("data:process", dataProcessorB)
```

is this possible ?
Thanks a lot

**Comment by hibiken** [comment]
@raynaudoe thank you for the question!

Is this similar to this other question #410?

**Comment by raynaudoe** [comment]
Thanks @hibiken , yeah, something like consumers groups.
The difference with the example on that issue is that, initially, my handlers (dataProcessorA, dataProcessorB ...) they all handle the same type of task but each processor analyzes let's say some aspect of the payload. Then the 'final' result is the sumatory of all the handler's outputs.

I'm sure that I can achieve the above using kafka or similar but since I'm using asynq for another component I thought I could achieve the same result without needing an extra package.

**Comment by hibiken** [comment]
I see. It sounds like this use case may benefit from a workflow feature like this one (#244)? Essentially you'd create a multiple tasks to handle multiple stages in your workflow.  

I'm planning to work on this laster half of this year so the feature is coming :)

**Comment by raynaudoe** [comment]
thanks! yeah, I really like the workflows idea! Looking forward to it :)
