### ISSUE TITLE
[BUG] Description of the bug

### ISSUE THREAD

**Issue by aukgit** [hibiken/asynq#427]
**Describe the bug**
Overflow build issue for x86 platform

```
# github.com/hibiken/asynq/internal/rdb
/go/pkg/mod/github.com/hibiken/asynq@v0.20.0/internal/rdb/rdb.go:386:7: constant 9223372036854775807 overflows int
/go/pkg/mod/github.com/hibiken/asynq@v0.20.0/internal/rdb/rdb.go:497:7: constant 9223372036854775807 overflows int
/go/pkg/mod/github.com/hibiken/asynq@v0.20.0/internal/rdb/rdb.go:739:7: constant 9223372036854775807 overflows int
/go/pkg/mod/github.com/hibiken/asynq@v0.20.0/internal/rdb/rdb.go:826:7: constant 9223372036854775807 overflows int
```

**To Reproduce**
Steps to reproduce the behavior (Code snippets if applicable):
1. Setup background : build on using docker

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/4561204/160698724-954d2fd6-2e78-4d11-9218-76bb8b4e68e2.png)

**Environment (please complete the following information):**
 - Ubuntu, Docker, Golang 17.8

**Additional context**
Probable solution for x86 arch use Int64 rather than Uint64 comparison

**Comment by hibiken** [comment]
This bug was fixed via #426 today. The fix should be included in the next release :)
