### ISSUE TITLE
scheduler fail

### ISSUE THREAD

**Issue by StevenSevenHHHH** [hibiken/asynq#430]
I started a once-a-minute execution of the scheduler, the execution succeeded several times will occasionally fail, the failure rate is very high, failure when the asynq handler is not called, failure web ui prompt "handler not found for task", if really handler is not configured that every time should not be executed successfully, but this is an occasional failure, can not understand. I configured scheduler, asynq handler server failure callbacks, but will not be triggered, but only in the web ui and redis on the number of failures increased, this is why, thank you for your reply

chinese：
我启动了一个一分钟执行一次的scheduler，执行成功几次就会偶尔出现失败，失败率很高，失败时候asynq 的handler没有被调用，失败web ui提示 “handler not found for task” ， 如果真的handler没配置那每一次都不应该执行成功，但这个却是偶尔失败，不能理解。我配置了scheduler、asynq handler server的失败回调，但是不会被触发，只是在web ui以及redis中上显示失败次数增加，这是为什么，感谢你的回复

**Comment by StevenSevenHHHH** [comment]
![asynq-retry-queue](https://user-images.githubusercontent.com/102236880/162128990-c28dbf88-3b5b-439a-a268-2da8b521ac07.jpg)
![asynq-retry](https://user-images.githubusercontent.com/102236880/162129008-15164963-04e4-4605-a991-48e19158e98c.jpg)

**Comment by StevenSevenHHHH** [comment]
The occasional failure case is that it actually just doesn't dispatch to my handler, it fails, and I debug the message at the handler entry and it doesn't output

**Comment by StevenSevenHHHH** [comment]
I would like to ask, how is this number of failures counted? As long as the first dispatch fails even if the subsequent retries succeed, the number of failures will be added up?

**Comment by StevenSevenHHHH** [comment]
I found the problem, it is my use of the error, I have enabled multiple workers locally connected to a redis, but these multiple workers are not the same registered handler, sometimes it will be dispatched to other unregistered workers will appear not found handler, sorry

**Comment by 54huige** [comment]
@StevenSevenHHHH 我有一个同样的问题，我这边注册了多个监听worker。会出现调度不到的情况，但是我确实需要不同监听消费者处理不同的路由，但是现在调度程序就没有区分多个Servers下不同的Type名称，导致提示“handler not found for task” 。
这种情况如何解决，有办法通过不同的队列名称去解决吗？还是有什么更好的办法，求指导
