### ISSUE TITLE
Can I get metadata from server context?

### ISSUE THREAD

**Issue by realmicro** [hibiken/asynq#435]
When I Use `client.EnqueueContext`, the context with my metadata,
In Server, Can I get client metadata from `ProcessTask` 's context?

**Comment by hibiken** [comment]
@realmicro thank you for the question!

The context you provide to `EnqueueContext` applies to the enqueue operation only (e.g. timeout/deadline for enqueue operation). If you need to provide metadata to Handler, use task payload instead. 
If you have some static metadata you want to provide to handler via context, you may be able to leverage [`Config.BaseContext`](https://pkg.go.dev/github.com/hibiken/asynq#Config.BaseContext)

**Comment by realmicro** [comment]
@hibiken OK, Thanks for your reply.
I have use task payload instead.
