### ISSUE TITLE
asynq tools not installing

### ISSUE THREAD

**Issue by jubel8180-cloudly** [hibiken/asynq#438]
after providing this command
go get -u github.com/hibiken/asynq/tools/asynq

show me this output
go get: installing executables with 'go get' in module mode is deprecated.
Use 'go install pkg@version' instead.

**Comment by hibiken** [comment]
Thanks for opening an issue! Did you encounter any issues when installing the executable binary? Or is this more of a documentation bug?

**Comment by cspyb** [comment]
I double check my testing env, it's my fault here.

**Comment by hibiken** [comment]
@cspyb I'm guessing that your comment is meant for issue #436?
