### ISSUE TITLE
[FEATURE REQUEST] list all available states in cmd tool help info

### ISSUE THREAD

**Issue by tonytony2020** [hibiken/asynq#444]
it not easy to remember all available state values

    active     pending    aggregating  scheduled  retry      archived   completed  

if I make a small change  https://github.com/hibiken/asynq/blob/master/tools/asynq/cmd/task.go#L22
from 

    taskListCmd.Flags().StringP("state", "s", "", "state of the tasks to inspect")
    ....

to 

    allStates := strings.Join([]string{
        Somewhere.ConstTaskStateActive,
        Somewhere.ConstTaskStatePending,
        ....
        ", "
    }
    taskListCmd.Flags().StringP("state", "s", "", fmt.Sprintf("state of the tasks to inspect, one of %s", allStates))
    ....

would you merge this pr?

**Comment by hibiken** [comment]
@tonytony2020 Thank you for the feedback!

I'm actually currently working on improving the help command output for the CLI (https://github.com/hibiken/asynq/tree/enhance/cli). Feel free to create a PR for that branch :)
