### ISSUE TITLE
[FEATURE REQUEST] Expose an option to change standard cron parser for a scheduler

### ISSUE THREAD

**Issue by SergeyNSW** [hibiken/asynq#447]
**Is your feature request related to a problem? Please describe.**
I'd like to have an ability to run a job every N seconds, the cron package used behind the scene allows to have extended (with seconds) or custom schedule parser, but the async uses default one.
**Describe the solution you'd like**
Is it possible to extend the asynq.SchedulerOpts so that it would accept custom cron.ScheduleParser and pass it as an option to the cron instance?
Thanks

**Comment by hibiken** [comment]
Upon looking, it seems like spec like `"@every 30s"` works without a custom schedule parser. Does that work for you?

**Comment by SergeyNSW** [comment]
yes, it works for me, thanks

**Comment by acaloiaro** [comment]
Hi @hibiken -- I know this issue is closed, but I think it might be worth considering a different option, which some users might find less surprising:

In `scheduler.go`

```go
- cron: cron.New(cron.WithLocation(loc)),
+ cron: cron.New(cron.WithLocation(loc), cron.WithSeconds()),
``` 

Which allows users to supply their cronspecs with the full six fields `* * * * * *`
