### ISSUE TITLE
[FEATURE REQUEST] choose EVAL for `func (r *RDB) runScript`

### ISSUE THREAD

**Issue by chenlujjj** [hibiken/asynq#450]
**Is your feature request related to a problem? Please describe.**
I am using this awesome lib in my work, however when I released my application to production, I found that the evalsha is forbidden in my company. 

**Describe the solution you'd like**
Maybe we can choose to use `eval` or `evalsha` in `func (r *RDB) runScript` and `func (r *RDB) runScriptWithErrorCode`.
It can be a bool parameter in `NewClient` function or something.

**Describe alternatives you've considered**

**Additional context**

**Comment by chenlujjj** [comment]
It turns out that some script calls `func (r *RDB) runScript` or `func (r *RDB) runScriptWithErrorCode` mentioned above, others call `func (s *Script) Run` directly, such as `res, err := dequeueCmd.Run(context.Background(), r.client, keys, argv...).Result()` in `rdb.go`.

**Comment by chenlujjj** [comment]
So there woule be more work than just modifying `func (r *RDB) runScript` and  `func (r *RDB) runScriptWithErrorCode`

**Comment by chenlujjj** [comment]
I have fored a repo: https://github.com/chenlujjj/asynq/tree/eval-script, and replaced all `Run` to `Eval`. It's just a quick and dirty update for my usage and should not be merged into main branch.

**Comment by hibiken** [comment]
@chenlujjj thank you for opening an issue!
Do you think you can keep using your fork?

**Comment by chenlujjj** [comment]
> @chenlujjj thank you for opening an issue! Do you think you can keep using your fork?

yes, it works now.
