### ISSUE TITLE
Test goleak is outdated VerifyNoLeaks -> VerifyNone

### ISSUE THREAD

**Issue by anupriya17** [hibiken/asynq#453]
The goleak made changes while ago and it was not updated in asynq test cases

https://github.com/hibiken/asynq/blob/245d4fe66370611e552d1fe6f17982c849edac97/server_test.go#L23

Please check the readme
[VerifyNone](https://github.com/uber-go/goleak#quick-start)

**Comment by hibiken** [comment]
@anupriya17 Thank you for pointing this out! Looks like we are still using goleak v0.10.0. We should update to the latest release and update to the newer API as suggested.

**Comment by MohabMohamed** [comment]
I would love to work on this issue.
@hibiken can you please assign it to me?

**Comment by MohabMohamed** [comment]
Done in #454 , @hibiken  please review.

**Comment by hibiken** [comment]
Thank you @MohabMohamed  and @anupriya17 🎉
