### ISSUE TITLE
[FEATURE REQUEST] Is there any way to do some specific action before periodic task enqueue?

### ISSUE THREAD

**Issue by ChihSeanHsu** [hibiken/asynq#456]
**Is your feature request related to a problem? Please describe.**
As title, I'm wondering is there any option or handler before periodic task enqueue?

**Describe the solution you'd like**
Maybe, we can solve this case just like [error-handling](https://github.com/hibiken/asynq/wiki/Periodic-Tasks#error-handling)

**Additional context**
IMO, we can implement this function in Enqueue part, not only for periodic task.

**Comment by hibiken** [comment]
@ChihSeanHsu thank you for creating a feature request.

What kind of action do you need to perform before enqueueing a task? I want to understand the motivation.

**Comment by ChihSeanHsu** [comment]
@hibiken Thanks for your prompt response.
We want to have a metrics to monitor the periodic enqueue count or some other actions (Currently, I have no another idea).
Although, we can just make this metrics by processing task part, but I just wonder is there any pre-action way not post-action.

**Comment by ChihSeanHsu** [comment]
@hibiken Great.
Thanks for your help!
What will the road map be about this small feature?
Or can I just submit a PR about it?

**Comment by hibiken** [comment]
@ChihSeanHsu Feel free to open a PR if you have bandwidth to work on it. Thanks :)

**Comment by ChihSeanHsu** [comment]
Hi @hibiken 
Here is the [PR](https://github.com/hibiken/asynq/pull/476), and feel free to review it thanks.

**Comment by hibiken** [comment]
Closed via #476. This feature will be included in the next release. Thank you @ChihSeanHsu !
