### ISSUE TITLE
[FEATURE REQUEST]  Periodic Tasks support customize cron logger

### ISSUE THREAD

**Issue by yxlimo** [hibiken/asynq#459]
i want to customize cron logger to get more info, but i can't do it with scheduler
```
return &Scheduler{
  cron:       cron.New(cron.WithLocation(loc)),
}
```

maybe we can add an option for schedulerOpts like
```
struct {
    CronLogger cron.Logger
    Logger Logger
    LogLevel LogLevel
}
```

or just use asynq logger wrapper, seems little strange, and it need to do many things to handle edge case.
```
type cronLoggerWrapper struct {
       logger Logger
}

func (l *cronLoggerWrapper) Info(msg string, keysAndValues ...interface{}) {
       l.logger.Info(msg, )
}
```

WDYT?

**Comment by hibiken** [comment]
@yxlimo Thank you for opening an issue! 
What kind of logs do you need?

**Comment by yxlimo** [comment]
> @yxlimo Thank you for opening an issue! What kind of logs do you need?

thank you for reply，i need logs like this
- every time cronjob started
- enqueue task success or failed

**Comment by hibiken** [comment]
> every time cronjob started

You can do this within your `Handler` code. If it's shared between multiple task types, I'd recommend using `MiddlewareFunc` to have that applied to multiple tasks. See [this wiki page](https://github.com/hibiken/asynq/wiki/Handler-Deep-Dive#using-middleware) for examples.

> enqueue task success or failed
Currently, you can provide ]`SchedulerOpts.EnqueueErrorHandler`](https://pkg.go.dev/github.com/hibiken/asynq#SchedulerOpts.EnqueueErrorHandler) but there's a open feature request to add callbacks to both before and after the enqueue event #456

**Comment by hibiken** [comment]
Closing this since it can be achieved using pre and post enqueue callbacks added in #476
