### ISSUE TITLE
[FEATURE REQUEST] Support compress task payload

### ISSUE THREAD

**Issue by linhbkhn95** [hibiken/asynq#463]
**Is your feature request related to a problem? Please describe.**
- Currently, I use some data as a task `asynq`, but it's payload size is big. So, I think whether `asynq` should support compress task payload when marshal task to save to redis.

**Describe the solution you'd like**
- use `gzip`... to compress task before storing to redis

**Describe alternatives you've considered**
No
**Additional context**
<img width="904" alt="Screen Shot 2022-05-13 at 10 57 30" src="https://user-images.githubusercontent.com/21085454/168208371-9386b9cf-f039-4347-a713-5c186751f427.png">

Redis memory usage always be high

**Comment by hibiken** [comment]
@linhbkhn95 Thank you for creating an issue!

In general, we recommend that you keep the memory footprint of each task small (e.g. payload contains IDs to various data). 
Is it possible to store the data elsewhere and refer to it via IDs?

**Comment by linhbkhn95** [comment]
yeah, I think so. Currently, I still choose a solution like your choice.
many thanks.

**Comment by linhbkhn95** [comment]
So I will close this issue
