### ISSUE TITLE
[FEATURE REQUEST] support getting state of task

### ISSUE THREAD

**Issue by jack-evans** [hibiken/asynq#466]
**Is your feature request related to a problem? Please describe.**

It may be possible that on API call I enqueue a task and return a 202, but I want to provide an API that would then allow to retrieve the state of task, I.e has it been completed, is it still in progress etc

**Describe the solution you'd like**

The client can get a task that has been enqueued and give the state of progress. 

**Describe alternatives you've considered**

Normally in a queuing system once something is taken off you don't then put it back on, might be a little out of scope of this project 🤔 

**Additional context**

**Comment by hibiken** [comment]
@jack-evans Thank you for creating an issue!

The package provide [`Inspector`](https://pkg.go.dev/github.com/hibiken/asynq#Inspector) type which allows you to query various information from the queue, including `TaskInfo`.
Calling `Inspector.GetTaskInfo` and inspecting `TaskInfo.State` should give you the current state of the task in question :)

LMK if you have questions!

**Comment by jack-evans** [comment]
Ahh was reading the client api doc rather than the inspector 🤦 thanks!
