### ISSUE TITLE
[BUG] Handler.ProcessTask return SkipRetry disabled

### ISSUE THREAD

**Issue by netor** [hibiken/asynq#471]
**Describe the bug**
Handler.ProcessTask return SkipRetry, but task retry again.

**To Reproduce**
Steps to reproduce the behavior (Code snippets if applicable):
1. Setup background processing ...
2. Enqueue tasks ...
3. See Error ...

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows10
 - Version of `asynq` package: v0.23.0

**Additional context**

**Comment by minhdtb-tanaakk** [comment]
I have the same issue, how can you fix it?
