### ISSUE TITLE
[FEATURE REQUEST] Self-Managed Retries

### ISSUE THREAD

**Issue by AlexCuse** [hibiken/asynq#472]
**Is your feature request related to a problem? Please describe.**
I would like to be able to leverage "processor managed" retries for specific tasks running through an asynq server.

**Describe the solution you'd like**
I will have a PR shortly for a `SelfManagedRetry` option that will override Retry/Retried logic to retry a task indefinitely (from asynq's perspective) allowing the processor to terminate by either returning success or SkipRetry. 

**Describe alternatives you've considered**
Looked at the options around "consuming retry count" and thought about figuring considered setting a high number of retries since looking at this within a fairly short expiration right now but came around to favoring something a little more direct.

There is a risk of tasks retrying indefinitely if not self-managed correctly but this should be difficult to fall into without using the option.

**Comment by hibiken** [comment]
@AlexCuse Thank you for creating an issue.

Have you taken a look at [`Config.IsFailure`](https://pkg.go.dev/github.com/hibiken/asynq#Config.IsFailure)? 
You can provide this function to determine whether the error returned from the `Handler` should be considered a failure. Non-failure error won't consume the retry count; You can leverage this feature to try task indefinitely if you so choose. 

See this wiki for more info (https://github.com/hibiken/asynq/wiki/Task-Retry#non-failure-error)

**Comment by AlexCuse** [comment]
I have looked at it @hibiken - the problem with most of what is there is that its not task type specific.  We have a subset of critical tasks that are "chained" so to speak and we really only want to change the behavior for those tasks - the idea is to retry up to an expiration that is encoded in the task payloads, and once the expiration is hit to move the task into a cancellation queue where processors will clean up any progress associated with the attempt.

Maybe another option could be to make the existing methods task-type aware?

**Comment by hibiken** [comment]
Can you define your own error type and include task type?

e.g.

```go
type TaskError struct {
    TaskType string
    // ... other metadata 
}

func (e *TaskError) Error() string { /* ... */ }

func IsFailure(err error) bool {
    taskErr, ok := err.(*TaskError)
    if !ok {
        return true // other errors are always considered failures
    }
    switch taskErr.TaskType {
    case "foo":
        // ... handle each task type differently       
    }
}

**Comment by AlexCuse** [comment]
We could I'm not sure how attractive it is as the number of registered processors in the system grows though.  Will think a bit about how far this could get us.

**Comment by hibiken** [comment]
I believe the options we offer now (`MaxRetry` option and `IsFailure` callback) are generic enough to accommodate most use cases. I don't see adding a new option to further customize retry logic.

**Comment by AlexCuse** [comment]
Thanks for the quick response @hibiken i disagree but we will be able to muddle through with what's there for awhile.  I have already changed the code and will probably open the PR anyway once I've tested it in a running system in case you change your mind, seems like a pretty simple change.
