### ISSUE TITLE
[FEATURE REQUEST] does it suport multi comsumers like kafka

### ISSUE THREAD

**Issue by zhuxubin01** [hibiken/asynq#478]
For example 

  I send a task to a queue, and I have multi micro service want to consume it and excute logic themself

**Comment by hibiken** [comment]
@zhuxubin01 Thank you for asking a question!

Currently Asynq doesn't have a feature like consumer group in Kafka. Please see my comment here (https://github.com/hibiken/asynq/issues/410#issuecomment-1059973170) from a similar issue.

Let me know if you have any follow up questions!
