### ISSUE TITLE
[BUG] Archived tasks prevent new tasks being queued when using TaskID

### ISSUE THREAD

**Issue by jt-voyager** [hibiken/asynq#492]
**Describe the bug**
If we have a task that has a TaskID, and it exhausts it's retry count, you cannot queue that task up again as it's considered a duplicate.

**To Reproduce**
1. Enqueue a task with a TaskID
2. Let it exhaust it's retry count
3. Observe it in the archived state
4. Try and enqueue another task with same TaskID
5. Observe it be rejected

**Expected behavior**
If a task is in the archive state, we should be able to enqueue a new task with that TaskID

**Screenshots**

**Environment (please complete the following information):**
 - OS: any
 - Version of `asynq` package: v0.23.0

**Comment by hibiken** [comment]
@jt-voyager Thank you for creating an issue. 
This is WAI (working as intended).
If you really need to enqueue another task with the same TaskID, then I suggest using [`Inspector.DeleteTask`](https://pkg.go.dev/github.com/hibiken/asynq#Inspector.DeleteTask) to ensure that the old task with the same ID is deleted.
