### ISSUE TITLE
[FEATURE REQUEST] Multiple queues with different workers

### ISSUE THREAD

**Issue by zerozh** [hibiken/asynq#493]
**Is your feature request related to a problem? Please describe.**
As the document described, the `queue` concept in asynq is actually `priority`. All tasks in different queues share the workers specified in Config. 

**Describe the solution you'd like**
With my scenario, I want the queue to be namespace, or a group of tasks. For example, I have different types of tasks(`order`/`sms`/`mail` etc) and they have their own workers(`order: 10, sms: 2, mail: 2`). These workers only consume the "queue" they want to deal with. That said, we only have 2 workers to run the mail tasks in parallel in case high concurrent traffics.

**Describe alternatives you've considered**
I can start different executable programs with different configs.
- A program only handle order queue with concurrency 10
- A program only handle sms queue with concurrency 2
- A program only handle mail queue with concurrency 2

I have to monitor several programs on my own with this alternatives. Instead, if asynq could provide the feature it would be great.

**Additional context**

**Comment by hibiken** [comment]
@zerozh Thank you for creating this issue! I'll consider adding an option to limit the concurrency for each queue.

In the meantime, we could use the approach you suggested with a single executable:
You could create a `asynq.Server` object for each queue with the desired concurrency and start all servers in one main.
Note: API is a little awkward (maybe we should consider moving `Handler` to be a part of `Config`), but this should work.

Example:
```go
package main

import (
	"log"
	"os"
	"os/signal"

	"github.com/hibiken/asynq"
	"golang.org/x/sys/unix"
)

func main() {
	redisConnOpt := asynq.RedisClientOpt{
		Addr: ":6379",
	}
	orderSrv := asynq.NewServer(redisConnOpt, asynq.Config{
		Concurrency: 10,
		Queues: map[string]int{
			"order": 1,
		},
	})
	smsSrv := asynq.NewServer(redisConnOpt, asynq.Config{
		Concurrency: 2,
		Queues: map[string]int{
			"sms": 1,
		},
	})
	mailSrv := asynq.NewServer(redisConnOpt, asynq.Config{
		Concurrency: 2,
		Queues: map[string]int{
			"mail": 1,
		},
	})

	orderHandler := asynq.NewServeMux()
	smsHandler := asynq.NewServeMux()
	mailHandler := asynq.NewServeMux()

	// ... [ommitted] handler regiseration

	if err := orderSrv.Start(orderHandler); err != nil {
		log.Fatal(err)
	}
	if err := smsSrv.Start(smsHandler); err != nil {
		log.Fatal(err)
	}
	if err := mailSrv.Start(mailHandler); err != nil {
		log.Fatal(err)
	}

	sigs := make(chan os.Signal, 1)
	signal.Notify(sigs, unix.SIGTERM, unix.SIGINT, unix.SIGTSTP)
	// Handle SIGTERM, SIGINT to exit the program.
	// Handle SIGTSTP to stop processing new tasks.
	for {
		s := <-sigs
		if s == unix.SIGTSTP {
			orderSrv.Stop() // stop processing new tasks
			smsSrv.Stop()
			mailSrv.Stop()
			continue
		}
		break // received SIGTERM or SIGINT signal
	}

	orderSrv.Shutdown()
	smsSrv.Shutdown()
	mailSrv.Shutdown()
}
```

Let me know if you have feedback or questions.

**Comment by zerozh** [comment]
@hibiken Thanks for the code snippet! That's super helpful.

**Comment by xylomo** [comment]
@hibiken was this actually complete or is expected to use the multiple server approach?
