### ISSUE TITLE
[BUG] discarding bad PubSub connection read i/o timeout

### ISSUE THREAD

**Issue by puyongcl** [hibiken/asynq#503]
when i import github.com/go-redis/redis/v8 v8.11.6-0.20220405070650-99c79f7041fc 
 a error keeps appearing: pubsub.go 159: discarding bad PubSub connection read i/o timeout
at github.com/hibiken/asynq v0.23.0

**Comment by jaekook-neonesia** [comment]
I have same issue.

**Comment by jaekook-neonesia** [comment]
Related to this issue?

Closing pubsub gracefully with cancellation context will log discarding connection
https://github.com/go-redis/redis/issues/2117

**Comment by puyongcl** [comment]
> I have same issue. Looked at logs and codes, one of task server hanged without any error, log message. After that, the client of the server pubsub connection error started(after 3 minutes)

my error was occured when server start, and keep every few second.I update go-redis to v8.11.5, it disappered.

**Comment by hibiken** [comment]
@puyongcl thank you for reporting! It sounds like an issue with the dependency. If anyone is encountering this issue, please upgrade to the latest version of go-redis and see if fixes the issue.

**Comment by dahvlhldle** [comment]
@hibiken redis 7 need `github.com/go-redis/redis/v9`,Is it possible to upgrade?
