### ISSUE TITLE
How Can I continue a Delay Task?

### ISSUE THREAD

**Issue by realmicro** [hibiken/asynq#512]
If I enqueue a task like this:

`client.Enqueue(task1, asynq.ProcessIn(24*time.Hour))`

When the task is not executed, I wanner do this task after 48*time.Hour, How Can I achieve this feature?

@hibiken

**Comment by hibiken** [comment]
@realmicro Thank you for opening an issue. You should be able to customize your retry delay by providing a custom function. See examples [here](https://github.com/hibiken/asynq/wiki/Task-Retry#customize-retry-delay).

**Comment by realmicro** [comment]
@hibiken Thanks for you reply.
I am not sure if this feature is my solution.
My English is poor, I am not sure I can describe my problem, Sorry for that.
My problem is, for example:
- My Order Service for creating order
- My MQ Service for handling order not paid after 30 minutes later
- If 30 minutes later, user want continue this order, I want extend the order time, maybe handle this order 1 hour later
How Can I achieve this feature?
