### ISSUE TITLE
[FEATURE REQUEST] Add Upgrade guide when there is a new release

### ISSUE THREAD

**Issue by mm2175** [hibiken/asynq#519]
I'm currently using version 0.18.6, how to upgrade to 0.23.0? I can't find any notes on this, is it compatiable(with retry and archive task)?

**Comment by hibiken** [comment]
@mm2175 Thank you for the question. Please take a look at our [release notes ](https://github.com/hibiken/asynq/releases). 
Feel free to reopen this issue if you have more questions.
