### ISSUE TITLE
[QUESTION] Does Concurrency parameter only work on same Golang process?

### ISSUE THREAD

**Issue by rendybjunior** [hibiken/asynq#530]
I tested `Concurrency: 1` configuration, and then I run multiple worker processes on different terminal tab.
The result of my experiment, the concurrency configuration only work for each process, but NOT across processes.

Is this observation accurate? Because the documentation does not explain much about the concurrency.

If the answer is yes, concurrency only work on each process, then if I have multiple workers running on different pods (let say 5 pods) with setting `Concurrency: 1`, this means I will have 5 concurrent tasks running.

Hope the question is clear enough. Thanks! @hibiken

**Comment by hibiken** [comment]
Yes, your observation is correct. 
The concurrency option controls how many active goroutines a `Server` can have.
