### ISSUE TITLE
[FEATURE REQUEST] The msg cannot be consumed by my expected worker.

### ISSUE THREAD

**Issue by Lilihx** [hibiken/asynq#551]
**Is your feature request related to a problem? Please describe.**

In our debug mod, we share a redis. So there are several workers, and I want to make breakpoints in my IDE.
In this situation, how can i ensure that the msg sent from my local producer was consumed by my local worker ？

**Describe the solution you'd like**

I do not know if there is any option now.

**Describe alternatives you've considered**

**Additional context**

**Comment by hibiken** [comment]
thanks @Lilihx for the question, and thanks @AMAN-BARBARIA for answering!

**Comment by XTeam-Wing** [comment]
> @Lilihx One way of achieving that could be to add prefix to the queue names.So each worker subscribes to different queue based on what prefix you set and then the producers can enqueue in specific queue?
> 
> We too share a common redis server for our local development and each developer use a different prefix set in the environment variable so the queue is different and messages are sent/consumed by the expected workers only.
But it conflicts with priority.
