### ISSUE TITLE
[QUESTION] Can i persist completed job information?

### ISSUE THREAD

**Issue by danvixent** [hibiken/asynq#553]
Can data about jobs that have been completed be persisted in asynq?

**Comment by chromosomaly** [comment]
https://github.com/hibiken/asynq/wiki/Task-Retention-and-Result

Use `asynq.Retention(1*time.Minute)` (or any other time.Duration)

**Comment by hibiken** [comment]
The `Retention` option keeps the job in Redis for the specified duration.
If you want to persist your job data durably and/or permanently, you could write a middleware to persist jobs when it's processed successfully.  
Thanks @danvixent for the question and thanks @chromosomaly for answering!

**Comment by danvixent** [comment]
Thanks y'all @chromosomaly @hibiken
