### ISSUE TITLE
[FEATURE REQUEST] Update Redis GO library to support Redis 7

### ISSUE THREAD

**Issue by abit2** [hibiken/asynq#570]
**Is your feature request related to a problem? Please describe.**
Steps to reproduce

1. Creating a redis cluster with redis 7. [link](https://redis.io/docs/management/scaling/)
2. Following the steps in wiki [link](https://github.com/hibiken/asynq/wiki/Redis-Cluster)
3. Run the enqueue code below.
```
client := asynq.NewClient(asynq.RedisClusterClientOpt{
		Addrs: []string{"localhost:7000", "localhost:7001", "localhost:7002", "localhost:7003", "localhost:7004", "localhost:7005"},
	})
	defer client.Close()

	// ------------------------------------------------------
	// Example 1: Enqueue task to be processed immediately.
	//            Use (*Client).Enqueue method.
	// ------------------------------------------------------

	task, err := tasks.NewEmailDeliveryTask(42, "some:template:id")
	if err != nil {
		log.Fatalf("could not create task: %v", err)
	}
	queues := []string{"q_1", "q_2", "q_3", "q_4"}
	for i := 0; i < 10000; i++ {
		que := queues[i%4]
		info, err := client.Enqueue(task, asynq.Queue(que))
		if err != nil {
			log.Fatalf("could not enqueue task: %v %s", err, que)
		}

		log.Printf("enqueued task: id=%s queue=%s", info.ID, info.Queue)
	}
```

**Describe the solution you'd like**
Seems to be related to the redis/v8 library results in error [link](https://github.com/go-redis/redis#installation)
Upgrading to redis/v9 might solve this?
```
error: SADD failed: got 4 elements in cluster info address, expected 2 or 3
```

**Additional context**
Following the steps above to figure out how to use asynq

**Comment by kamikazechaser** [comment]
go-redis/v9 is not backward afaik. This would be a breaking change.

**Comment by kamikazechaser** [comment]
Related to #602
