### ISSUE TITLE
Regular release schedule

### ISSUE THREAD

**Issue by kamikazechaser** [hibiken/asynq#572]
Go mod, by default, fetches versions as per tags. The last tag was back in April and there have since been couple of fixes.

**Comment by hibiken** [comment]
Thanks for raising this issue. 
Agreed, we need to ensure that fixes get released in a timely manner. 
Quarterly release sounds reasonable to me. Let me try to schedule that from the next year.

**Comment by hibiken** [comment]
v0.24.0 is now released. We'll establish a regular release cadence (bi-monthly or so) this year.

**Comment by kamikazechaser** [comment]
Thanks!
