### ISSUE TITLE
[BUG] hanlder not found for task

### ISSUE THREAD

**Issue by mindon** [hibiken/asynq#574]
**Describe the bug**
hanlder not found for task happens sometimes

**To Reproduce**
1. register 3 different patterns width HandleFunc
2. submit 3 tasks with different patterns used above
3. sometimes it retrying with "hanlder not found" error

**Expected behavior**
Not such a not-found-error

**Screenshots**
<img width="761" alt="image" src="https://user-images.githubusercontent.com/510257/202425965-5c6a9e36-c586-499d-be5b-1d255cf64e64.png">

**Environment (please complete the following information):**
 - OS: CentOS
 - asynq v0.23.0

**Comment by mindon** [comment]
this error report inside ErrorHandler of a server without any handler

**Comment by risyadaji** [comment]
hi @mindon could you explain how you fix this issue? i have same problem

thanks before

**Comment by mindon** [comment]
> 

the queques and handlers should be all matched

**Comment by mindon** [comment]
> hi @mindon could you explain how you fix this issue? i have same problem
> 
> thanks before


@risyadaji  all the queques and handlers should be matched

**Comment by risyadaji** [comment]
> > hi @mindon could you explain how you fix this issue? i have same problem
> > thanks before
> 
> @risyadaji all the queques and handlers should be matched

yup, i already found the way. Thanks for the insight!

**Comment by mindon** [comment]
> @risyadaji @mindon what do you mean by "all the queques and handlers should be matched". Can you please elaborate.

it means: if there's a task request without a relative handler, you will surely get this error.

**Comment by risyadaji** [comment]
> @risyadaji @mindon what do you mean by "all the queques and handlers should be matched". Can you please elaborate.

@mohit-singh-pepper my workaround is when enqueueing the task i put task name and also the queue name (using `asynq.Queue(queueName)`).
