### ISSUE TITLE
[FEATURE REQUEST] Task Priority

### ISSUE THREAD

**Issue by 27149chen** [hibiken/asynq#579]
**Is your feature request related to a problem? Please describe.**
I have three queues processing tasks in parallel, but in each queue, task are processed serially with priority

**Describe the solution you'd like**
Introduce Task Priority in queue

**Describe alternatives you've considered**

**Additional context**

**Comment by hibiken** [comment]
Thanks for opening a FR. Unfortunately I don't think we will add support for task priorities within a single queue. 
Please use multiple queues and assign priorities to each queue. 
Thanks!
