### ISSUE TITLE
RedisFailoverClientOpt doesn't have SentinelUsername field

### ISSUE THREAD

**Issue by khasanovbi** [hibiken/asynq#583]
RedisFailoverClientOpt doesn't have SentinelUsername field

**Comment by vernonr3** [comment]
Hello Ken (@hibiken)
Fix this issue in one sense is simply about adding the SentinelUsername to the struct.  However in doing this a number of underlying issues are exposed:

- should the redis-sentinel URI scheme change from redis-sentinel://[:password@]host1[:port][,host2:[:port]][,hostN:[:port]][?master=masterName] to include username redis-sentinel://[username][:password@]host1[:port][,host2:[:port]][,hostN:[:port]][?master=masterName] ?
- if this is case should the other URI schemes also change?
- there aren't mocked tests for the redis interface. The current tests rely on a real redis instance being available. Code appears for the standalone and cluster variants but **not** for the sentinel variants.

What is the policy here? Should we fix it on a "simple" basis - or make the fix more complex by working to improve the rest of the testing code? I'm wondering how big an issue this is for the user community?
Thanks

**Comment by shuqingzai** [comment]
Can this problem be fixed in the near future? @hibiken 

We are using sentinel mode but cannot configure SentinelUsername in asynq

**Comment by Skwol** [comment]
Added [PR](https://github.com/hibiken/asynq/pull/924) for this issue.

Since asynq uses `github.com/redis/go-redis/v9` you can create your own options as a workaround. It will look like that:
```
// asynq does not support multiple users via their default asynq.FailoverOptions, so we need to create our own
type asynqRedisClientOpt struct {
	clientName             string
	masterName             string
	sentinelUsername       string
	sentinelPassword       string
	sentinelAddrsWithPorts []string
	username               string
	password               string
	db                     int
	tlsConfig              *tls.Config
	dialTimeout            time.Duration
}

func (a asynqRedisClientOpt) MakeRedisClient() interface{} {
	return redis.NewFailoverClient(&redis.FailoverOptions{
		ClientName:       a.clientName,
		MasterName:       a.masterName,
		SentinelUsername: a.sentinelUsername,
		SentinelPassword: a.sentinelPassword,
		SentinelAddrs:    a.sentinelAddrsWithPorts,
		Username:         a.username,
		Password:         a.password,
		DB:               a.db,
		TLSConfig:        a.tlsConfig,
		DialTimeout:      a.dialTimeout,
	})
}
```

**Comment by kamikazechaser** [comment]
> you can create your own options as a workaround. 

I also recommend this. Gives users a lot more flexibility. It was a lesser known possibility so I added it to the documentation last week.

https://github.com/hibiken/asynq/wiki/Getting-Started#reuse-an-existing-go-redis-connection-pool


As for this issue specifically, I think we can just add the field to the struct and more complex redis connection setups can use a similar approach above.
