### ISSUE TITLE
[BUG] asynq cli ignore cluster param in config file

### ISSUE THREAD

**Issue by khasanovbi** [hibiken/asynq#587]

**Comment by hibiken** [comment]
It should be bound by these two lines: https://github.com/hibiken/asynq/blob/c08f142b5666b5983db9bd84764b7917b953d3a2/tools/asynq/cmd/root.go#L320-L321

Would you mind verifying this bug?

**Comment by khasanovbi** [comment]
I don't see that `viper.GetBool("cluster")` used in code, instead of that flag used directly

**Comment by hibiken** [comment]
Ah, you're right. Thanks for filing this issue
