### ISSUE TITLE
Question about task ID

### ISSUE THREAD

**Issue by VolunPotest** [hibiken/asynq#592]
Hi!
I have a question about Task ID.

We can receive it when we create a task and send it to the Enqueue.

But I don't see the ID of the task in handling function, we only have *asynq.Task.
My question is: Is it possible to retrieve taskID in the handle function? 

I think it will be really helpful (especially for a logging) 
Thank you!

**Comment by hibiken** [comment]
You can get it by calling [`GetTaskID`](https://pkg.go.dev/github.com/hibiken/asynq#GetTaskID) passing in the context.

```go
func MyHandler(ctx context.Context, task *asynq.Task) error {
     id, ok := asynq.GetTaskID(ctx)
     // ... rest of the handler code omitted.
}
```

**Comment by VolunPotest** [comment]
Hi. Thank you for the response.
Do you consider returning the whole metadata struct? 
Something like this?

```
// GetMetadata extracts metadata from a context, if any.
func GetMetadata(ctx context.Context) (metadata taskMetadata, ok bool) {
	metadata, ok = ctx.Value(metadataCtxKey).(taskMetadata)
	return
}
```
