### ISSUE TITLE
[FEATURE REQUEST] Do you consider to return the whole metadata struct?

### ISSUE THREAD

**Issue by VolunPotest** [hibiken/asynq#594]
Hi. Thank you for the response for the previous issue.

Do you consider returning the whole metadata struct?
Something like this?

// GetMetadata extracts metadata from a context, if any.
func GetMetadata(ctx context.Context) (metadata taskMetadata, ok bool) {
	metadata, ok = ctx.Value(metadataCtxKey).(taskMetadata)
	return
}

Thank you

**Comment by hibiken** [comment]
At this point, I don't have a plan to expose the whole task metadata.

Let me know if you have a specific use case for this.
