### ISSUE TITLE
[BUG] asynq: task lease expired ，What does it mean？

### ISSUE THREAD

**Issue by XTeam-Wing** [hibiken/asynq#612]
What is the reason for this error? If the queue is wrong, no error information is seen.
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/25416365/218240024-ec9b7c41-f05a-4fc7-b7e5-4e22aa52e256.png">

**Comment by linhbkhn95** [comment]
hi @XTeam-Wing 
I think your code or infra will catch some problems
```
// ErrLeaseExpired error indicates that the task failed because the worker working on the task
// could not extend its lease due to missing heartbeats. The worker may have crashed or got cut off from the network.
```
I see the queue does not exist error in the image above => no worker processed this task => expired time for processing.
Im not sure.
Feel free provide your code here to have full overview context.

**Comment by XTeam-Wing** [comment]
```
	srv := asynq.NewServer(
		asynq.RedisClientOpt{
			Addr:         conf.Redis.Addr,
			Password:     conf.Redis.Password,
			DB:           conf.Redis.DB,
			ReadTimeout:  -1,
			WriteTimeout: 0,
		},

		asynq.Config{
			Concurrency: concurrent,
			Queues: map[string]int{
				"test":     1,
			},
			StrictPriority: true,
			ErrorHandler:   asynq.ErrorHandlerFunc(reportError),
		},
	)
```
<img width="778" alt="image" src="https://user-images.githubusercontent.com/25416365/221121901-66d94313-9ac9-4421-afa3-6bea6d374ede.png">

```
func handledemo(ctx context.Context, t *asynq.Task) error {

	var d model.Arg
	if err := json.Unmarshal(t.Payload(), &d); err != nil {
		logger.Error(err)
		return err
	}
	
	return nil
}
```
I think mux.HandleFunc should return a clear error. Users can locate where the error occurred, thank you for your reply.

**Comment by linhbkhn95** [comment]
Can you show the enqueued task? We should map the handler with task type correctly.

**Comment by XTeam-Wing** [comment]
> Can you show the enqueued task? We should map the handler with task type correctly.

Hi, I got a more specific error

```
x-worker  | asynq: pid=928 2023/03/08 11:15:45.904045 WARN: Lease reset failed for f0686598-bf18-4e67-8263-a6983d5dfc95; lease deadline: 2023-03-08 19:15:32.128419658 +0800 CST m=+165249.263673317
```
<img width="1541" alt="image" src="https://user-images.githubusercontent.com/25416365/223762368-5e3f3c84-9612-40d8-a371-20bf131e3223.png">
I would like to ask what this means。

**Comment by XTeam-Wing** [comment]
@linhbkhn95 hi,master.
<img width="756" alt="image" src="https://github.com/hibiken/asynq/assets/25416365/9e4423a6-fff3-4b2f-96c6-ea7c49ec757a">

i think the handler is np.

**Comment by Xenov-X** [comment]
@XTeam-Wing - Did you find a solution to this?

**Comment by XTeam-Wing** [comment]
> @XTeam-Wing - Did you find a solution to this?

not yet,but I made some changes and this feature doesn't affect me

**Comment by william9x** [comment]
@XTeam-Wing I'm facing the same issues, do you mind sharing what changes did you make? Thank you!
