### ISSUE TITLE
[BUG] Wiki docs use "SetDefaultOptions" when it's deprecated

### ISSUE THREAD

**Issue by sushi30** [hibiken/asynq#618]
**Describe the bug**
It appears `SetDefaultOptions` was deprecated. It is still referenced in the docs: https://github.com/hibiken/asynq/wiki/Task-Retry#customize-task-max-retry

I did not change because I am a new user to the library so I am not sure what is the correct fix for this doc.

**Comment by fivezjd** [comment]
The latest version has three methods to set MaxRetry:

- `t1 := NewTask("shometype", nil, MaxRetry(10))`
- `client.Enqueue(t1, MaxRetry(10))`
- `client.EnqueueContext(context.Background(), t1, MaxRetry(10))`
The latter two methods will override the former one. [here](https://github.com/hibiken/asynq/blob/cc777ebdaa62b69bd6e985fa97117b854e7d1cd6/client.go#L246)

**Comment by hibiken** [comment]
Thanks for reporting this issue. Fixed :)
