### ISSUE TITLE
How do I set the interval between asyncq retries? 

### ISSUE THREAD

**Issue by yuzihui** [hibiken/asynq#633]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bfwbbrj** [comment]
Set the [RetryDelayFunc](https://github.com/hibiken/asynq/blob/cc777ebdaa62b69bd6e985fa97117b854e7d1cd6/server.go#L110). If not set, an exponential backoff algorithm based implementation will be used to calculate the retry interval.
