### ISSUE TITLE
[BUG] Use a custom redis client that will panic if redis close

### ISSUE THREAD

**Issue by shuqingzai** [hibiken/asynq#635]
**Describe the bug**
If you implement the `asynq.RedisConnOpt` interface and provide a custom redis client, `Ctrl + C` stops the `asynq.Server` and `asynq.Subscriber` panics

**To Reproduce**
Steps to reproduce the behavior (Code snippets if applicable):
1. Implement the `asynq.RedisConnOpt` interface and provide a custom redis client
2. Instantiate `asynq.Server` and set up a custom redis client
3. Start the Server
4. Stop custom redis client and `asynq.RedisConnOpt` return nil
5. Ctrl + C stops the Server,  `asynq.Subscriber` panics

**Expected behavior**

**Can support custom providing redis client instead of panic**

Because asynq will start multiple redis clients, and redis will also be used in my project, I hope that only one redis client can be instantiated for unified management and reuse clients

**Screenshots**

1. my redis client
> Implement the asynq.RedisConnOpt interface
>

![image](https://user-images.githubusercontent.com/44406033/229015867-ebd7ca78-4f14-4e25-a636-96723f80edef.png)

stop custom redis client  will return nil

3. `asynq.Subscriber` panics
![image](https://user-images.githubusercontent.com/44406033/229016233-9ebc1786-9358-482d-a861-f1551ee53c82.png)

![image](https://user-images.githubusercontent.com/44406033/229017169-cfcc376e-b364-46cf-a530-98207472156b.png)

Because `my redis client` returns nil ??

**Environment (please complete the following information):**
 - OS: [e.g. MacOS, Linux]
 ```shell
MacOS
```
 - Version of `asynq` package [e.g. v1.0.0]
 ```shell
v0.24.0
```

**Additional context**

**Comment by bfwbbrj** [comment]
@shuqingzai My guess would be the [msg](https://github.com/hibiken/asynq/blob/cc777ebdaa62b69bd6e985fa97117b854e7d1cd6/subscriber.go#L83) is nil. And this is related to to the pubsub returned by your custom redis's [Subscribe](https://github.com/hibiken/asynq/blob/cc777ebdaa62b69bd6e985fa97117b854e7d1cd6/internal/rdb/rdb.go#L1451). Since I have no idea which lib you are using, you probably need to check your lib's implementation.

**Comment by shuqingzai** [comment]
> @shuqingzai My guess would be the [msg](https://github.com/hibiken/asynq/blob/cc777ebdaa62b69bd6e985fa97117b854e7d1cd6/subscriber.go#L83) is nil. And this is related to to the pubsub returned by your custom redis's [Subscribe](https://github.com/hibiken/asynq/blob/cc777ebdaa62b69bd6e985fa97117b854e7d1cd6/internal/rdb/rdb.go#L1451). Since I have no idea which lib you are using, you probably need to check your lib's implementation.

@bfwbbrj First of all, thank you for answering my question

1. What do you mean by library?
2. I have not changed any configuration and the payload field has not been modified. I just switch my own Redis client back to asynq's built-in implementation and there will be no panic, but using my own implementation will cause panic

**Comment by bfwbbrj** [comment]
>What do you mean by library? 

The redis client implementation that you are using.

>I have not changed any configuration and the payload field has not been modified. I just switch my own Redis client back to asynq's built-in implementation and there will be no panic, but using my own implementation will cause panic

It should be related to the [Subscribe](https://github.com/hibiken/asynq/blob/cc777ebdaa62b69bd6e985fa97117b854e7d1cd6/internal/rdb/rdb.go#L1451) method of your redis client implementation. Can you share which redis client implementation you are using?

**Comment by shuqingzai** [comment]
> > What do you mean by library?
> 
> The redis client implementation that you are using.
> 
> > I have not changed any configuration and the payload field has not been modified. I just switch my own Redis client back to asynq's built-in implementation and there will be no panic, but using my own implementation will cause panic
> 
> It should be related to the [Subscribe](https://github.com/hibiken/asynq/blob/cc777ebdaa62b69bd6e985fa97117b854e7d1cd6/internal/rdb/rdb.go#L1451) method of your redis client implementation. Can you share which redis client implementation you are using?

Observe my screenshot, using go-redis's built-in interface analysis

See: https://github.com/redis/go-redis/blob/v8/universal.go#L208

<img width="818" alt="image" src="https://user-images.githubusercontent.com/44406033/229303612-afa5a458-2da1-46a1-96ba-5e591fc8f0f5.png">

**Comment by bfwbbrj** [comment]
> Observe my screenshot, using go-redis's built-in interface analysis
> 
> See: https://github.com/redis/go-redis/blob/v8/universal.go#L208

所以你的`m.redisClient`也是用`https://github.com/redis/go-redis/` 这个库的客户端吗？你现在的问题是你如果在`MakeRedisClient`里返回一个nil，在关服务器的时候会panic？

**Comment by shuqingzai** [comment]
> > Observe my screenshot, using go-redis's built-in interface analysis
> > See: https://github.com/redis/go-redis/blob/v8/universal.go#L208
> 
> 所以你的`m.redisClient`也是用`https://github.com/redis/go-redis/` 这个库的客户端吗？你现在的问题是你如果在`MakeRedisClient`里返回一个nil，在关服务器的时候会panic？
@bfwbbrj 
1. Yes
2. Hmm, maybe I closed the Redis client first?

**Comment by bfwbbrj** [comment]
> 2. Hmm, maybe I closed the Redis client first?

Is it possible for you not to close the Redis client and leave the work to asynq? Currently if you closed the redis client before you shutdown the asynq, [msg](https://github.com/hibiken/asynq/blob/cc777ebdaa62b69bd6e985fa97117b854e7d1cd6/subscriber.go#L83) will be nil since the channel is already closed. I will create a pr to fix this but since rn prs are not being reviewed and merge. I suggest that you let asynq do the client closing if possible.

**Comment by kamikazechaser** [comment]
If the new API (NewClientFromRedisClient) is used, then attempting to close the client through asynq will return an error https://github.com/hibiken/asynq/blob/master/client.go#L321.

A warning has also been added to guide users on this change. I would recommend moving to the new API and handling the closing on your own.

For now, I will close this Issue.
