### ISSUE TITLE
[FEATURE REQUEST] need another way to set RedisClientOpt 

### ISSUE THREAD

**Issue by lypro09539** [hibiken/asynq#639]
**Is your feature request related to a problem? Please describe.**
because our redis is configured on apollo，neither host nor pwd is exposed to applications。Each application specify redis name through our own lib,  and got a Redis Client instance (go-redis Redis Client)

**Describe the solution you'd like**
is there any way to use common redis client implementation to set redis backend instead of only RedisClientOpt ?   thanks.

**Comment by bfwbbrj** [comment]
Can you share how you get your redis client? You should be able to implement`RedisConnOpt` to use custom client

**Comment by lypro09539** [comment]
> Can you share how you get your redis client? You should be able to implement`RedisConnOpt` to use custom client

sorry, my fault. After intstall asynq and read source code I realized I could.
