### ISSUE TITLE
How to ensure that the tasks in redis will not be lost after the service stops for a long time

### ISSUE THREAD

**Issue by fms5cmS** [hibiken/asynq#650]
When i stop my server a long time, the tasks in redis lost, and tell me "[queue](asynq: queue not found)".

Do i need some config for this ?

**Comment by kamikazechaser** [comment]
Are you persisting your redis data between restarts?

**Comment by fms5cmS** [comment]
I just restarted my server by `kill -15 server` not Redis, so I do not need to persist Redis data.

Is the problem that I put the asynq server and client in the same application which I restarted?

**Comment by kamikazechaser** [comment]
You need to persist redis data if you want don't want to lose tasks. Start your redis server with `redis-server --save 60 1 --loglevel warning`.

**Comment by ioannidesalex** [comment]
That's not really an issue with asynq.
