### ISSUE TITLE
RedisClusterClientOpt  missing DB

### ISSUE THREAD

**Issue by aep** [hibiken/asynq#656]
Shouldnt RedisClusterClientOpt have  a DB param akin to RedisClientOpt ?
This seems to be a mistake, since the asynq cli DOES support db for cluster

**Comment by liran** [comment]
hi, Redis Cluster does not support multiple databases like the standalone version of Redis. We only support database 0 ; the SELECT command is not allowed.

[refer](https://www.google.com/search?q=redis+cluster+multiple+databases&oq=redis+cluster+mu&aqs=chrome.0.69i59j69i57.8004j0j7&sourceid=chrome&ie=UTF-8)

**Comment by aep** [comment]
ah i see, thanks.
