### ISSUE TITLE
[BUG] Latest version of asynq breaks asynq CMD

### ISSUE THREAD

**Issue by abezzub** [hibiken/asynq#686]
**Describe the bug**
This is a follow up to https://github.com/hibiken/asynqmon/issues/302 I cannot use `cmd` with asynq:
```
github.com/hibiken/asynq/tools/asynq/cmd
../../pkg/mod/github.com/hibiken/asynq/tools@v0.0.0-20230708040154-123d560a4488/asynq/cmd/root.go:369:20: 
cannot use c (variable of type "github.com/go-redis/redis/v8".UniversalClient) as "github.com/redis/go-redis/v9".UniversalClient value in argument to rdb.NewRDB: 
"github.com/go-redis/redis/v8".UniversalClient does not implement "github.com/redis/go-redis/v9".UniversalClient (missing method ACLDryRun)
```

**To Reproduce**

After upgrading to Asynq 0.24.1 and Asynqmon 0.7.2 I am getting the error above when I am trying to build the app that uses https://github.com/hibiken/asynq/tree/master/tools/asynq. Looks like Redis v8 is still used here:
https://github.com/hibiken/asynq/blob/master/tools/asynq/cmd/root.go#L19

**Environment (please complete the following information):**
 - OS: MacOS
 - Version of `asynq` package: 0.24.1

**Comment by hibiken** [comment]
@abezzub Thanks for reporting. PR welcome for this fix!
