### ISSUE TITLE
asynq: pid=1  WARN: recoverer: could not move task to archive: INTERNAL_ERROR: redis eval error: NOT FOUND[BUG] Description of the bug

### ISSUE THREAD

**Issue by 10-RongHui** [hibiken/asynq#690]
队列消费的时候，经常报错，如：asynq: pid=1 2023/07/21 05:57:34.423235 WARN: recoverer: could not move task to archive: INTERNAL_ERROR: redis eval error: NOT FOUND，请问有知道原因的吗？https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
![Uploading 20230721143810.jpg…]()

**Comment by hibiken** [comment]
@10-RongHui  Would you mind translating this in English (I cannot read Chinese, sorry). And please put more descriptive text in issue title.
Feel free to reopening this with more info, closing this until then.
