### ISSUE TITLE
[BUG] Task disappear after processing

### ISSUE THREAD

**Issue by bahattincinic** [hibiken/asynq#716]
**Describe the bug**

When I add a new task to the queue, I can see it until it's processed. However, once the task is processed, it disappears. I'm unable to access task information using the following code when the task is completed:

```golang
ins := asynq.NewInspector(asynq.RedisClientOpt{Addr: "localhost:6379"})
info, err := ins.GetTaskInfo("default", id)
```

If the task is completed, the `GetTaskInfo` function returns an `asynq: task not found error`. Additionally, the `ListCompletedTasks` function returns an empty list. This behavior is also observed in the Asynqmon Web UI.

**To Reproduce**

The example code is so simple. I directly used the example code for simulating the problem.

```golang
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"

	"github.com/hibiken/asynq"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
)

var (
	log *zap.Logger
)

// A list of task types.
const (
	TypeWelcomeEmail  = "email:welcome"
	TypeReminderEmail = "email:reminder"
)

// Task payload for any email related tasks.
type emailTaskPayload struct {
	// ID for the email recipient.
	UserID int
}

func NewWelcomeEmailTask(id int) (*asynq.Task, error) {
	payload, err := json.Marshal(emailTaskPayload{UserID: id})
	if err != nil {
		return nil, err
	}
	return asynq.NewTask(TypeWelcomeEmail, payload), nil
}

func NewReminderEmailTask(id int) (*asynq.Task, error) {
	payload, err := json.Marshal(emailTaskPayload{UserID: id})
	if err != nil {
		return nil, err
	}
	return asynq.NewTask(TypeReminderEmail, payload), nil
}

func HandleWelcomeEmailTask(ctx context.Context, t *asynq.Task) error {
	var p emailTaskPayload
	if err := json.Unmarshal(t.Payload(), &p); err != nil {
		return err
	}
	fmt.Printf(" [*] Send Welcome Email to User %d", p.UserID)
	return nil
}

func HandleReminderEmailTask(ctx context.Context, t *asynq.Task) error {
	var p emailTaskPayload
	if err := json.Unmarshal(t.Payload(), &p); err != nil {
		return err
	}
	fmt.Printf(" [*] Send Reminder Email to User %d", p.UserID)
	return nil
}

func initClient() {
	client := asynq.NewClient(asynq.RedisClientOpt{Addr: "localhost:6379"})

	t1, err := NewWelcomeEmailTask(42)
	if err != nil {
		log.Fatal("NewWelcomeEmailTask failed", zap.Error(err))
		os.Exit(1)
	}

	t2, err := NewReminderEmailTask(42)
	if err != nil {
		log.Fatal("NewReminderEmailTask failed", zap.Error(err))
		os.Exit(1)
	}

	// Process the task immediately.
	info, err := client.Enqueue(t1)
	if err != nil {
		log.Fatal("Enqueue failed", zap.Error(err))
		os.Exit(1)
	}
	log.Info(" [*] Successfully enqueued task: %+v", zap.Any("info", info), zap.String("id", info.ID))

	info2, err := client.Enqueue(t2)
	if err != nil {
		log.Fatal("Enqueue failed", zap.Error(err))
		os.Exit(1)
	}
	log.Info(" [*] Successfully enqueued task: %+v", zap.Any("info", info2), zap.String("id", info2.ID))
}

func initServer() {
	srv := asynq.NewServer(
		asynq.RedisClientOpt{Addr: "localhost:6379"},
		asynq.Config{
			Concurrency: 10,
		},
	)

	mux := asynq.NewServeMux()
	mux.HandleFunc(TypeWelcomeEmail, HandleWelcomeEmailTask)
	mux.HandleFunc(TypeReminderEmail, HandleReminderEmailTask)

	if err := srv.Run(mux); err != nil {
		log.Fatal("run failed", zap.Error(err))
		os.Exit(1)
	}
}

func setupLog() {
	zc := zap.NewDevelopmentConfig()
	zc.Level = zap.NewAtomicLevelAt(zapcore.DebugLevel)
	zc.OutputPaths = []string{"stdout"}

	zlog, err := zc.Build()
	if err != nil {
		panic(err)
	}
	log = zlog
}

func main() {
	setupLog()
	initClient()
	initServer()
}
```

**Expected behavior**

I expect to be able to access information about the task after it is finished, even if it has been successfully processed.

**Screenshots**
<img width="1508" alt="Screen Shot 2023-08-04 at 15 40 41" src="https://github.com/hibiken/asynq/assets/1684999/3bd6d08c-4544-450d-8a5c-63e227257572">

<img width="1512" alt="Screen Shot 2023-08-04 at 15 40 47" src="https://github.com/hibiken/asynq/assets/1684999/32d519f8-bf7b-449e-8217-ce1dcb94e95f">

<img width="621" alt="Screen Shot 2023-08-04 at 16 02 19" src="https://github.com/hibiken/asynq/assets/1684999/8a548e8e-ed0e-4d3c-80cf-a263e00fb41d">

<img width="938" alt="Screen Shot 2023-08-04 at 16 03 00" src="https://github.com/hibiken/asynq/assets/1684999/934eda4e-53cf-49d8-9a7b-4884c65758f0">

<img width="1464" alt="Screen Shot 2023-08-04 at 16 06 34" src="https://github.com/hibiken/asynq/assets/1684999/b5a0f594-4420-4f23-a3e8-b22cb17acd35">

**Environment (please complete the following information):**
 - OS: Mac
 - asynq: v0.24.1
 - golang:  1.19.3, 1.20.7
 - redis: 7.0, 5.0

**Comment by bahattincinic** [comment]
i've also tested this project https://github.com/koddr/tutorial-go-asynq/tree/master Result is still the same 🤔 

<img width="1259" alt="Screen Shot 2023-08-04 at 18 48 44" src="https://github.com/hibiken/asynq/assets/1684999/10a5eb01-a7a5-453d-8d21-f11e9e719c85">
<img width="1509" alt="Screen Shot 2023-08-04 at 18 49 00" src="https://github.com/hibiken/asynq/assets/1684999/d81a08ae-1352-4986-bbfa-915fe82b894d">

**Comment by vijaysainagavamsi** [comment]
Hello @bahattincinic,

I hope this message finds you well. By default, when a task is completed, the associated information is deleted. However, I understand that in some cases, it might be essential to retain the task information even after its completion.

To achieve this, you can utilize the "Retention" option when enqueuing the task. Allow me to provide you with an example:

`info2, err := client.Enqueue(t2, asynq.Retention(5*time.Minute))`

By setting the retention duration to 5 minutes in this case, the information about the task will be retained for an additional 5 minutes even after it is completed. This could be beneficial if you require access to the task details for a short period after completion.

**Comment by bahattincinic** [comment]
Hi @vijaysainagavamsi,

I've tested with `asynq.Retention`. it worked. thank you 😊
