### ISSUE TITLE
asynqmon没问题能访问；但是里面没有任何信息；提示No entries found at this time.

### ISSUE THREAD

**Issue by lxx254185251** [hibiken/asynq#747]
第一个问题：我也有UTC时间问题；和671、295他们的问题一样
第二个问题：不知道是不是因为第一个问题引起的；就像标题说的那样；能访问；但是没有信息；我确信我有写延时消息队列
![image](https://github.com/hibiken/asynq/assets/87219611/ab29c030-8978-4312-8f52-c3f7c266500d)

**Comment by kamikazechaser** [comment]
Duplicate of #671.
