### ISSUE TITLE
[FEATURE REQUEST] Support for dragonfly

### ISSUE THREAD

**Issue by sxwebdev** [hibiken/asynq#769]
Hello. Thank you for the excellent library that helps implement a high-quality task manager.

Recently, Dragonfly released full support for BullMQ.

[https://www.dragonflydb.io/blog/running-bullmq-with-dragonfly](https://www.dragonflydb.io/blog/running-bullmq-with-dragonfly)

Currently, your library only has support for redis. Are you planning to implement dragonfly support?

Now when I try to connect to Dragonfly I get the following error

```
UNKNOWN: redis eval error: ERR Error running script (call to a8153319360adc71cdc370107f8ab9786f204765): @user_script:7: script tried accessing undeclared key
```

**Comment by kamikazechaser** [comment]
Dragonfly is only a `partial` drop in replacement for redis. Not all redis features have been implemented. Moreover, `go-redis` would need to add any special support for Dragonfly if any. Untill then, the scope of this library would be redis.
