### ISSUE TITLE
Other serialization format

### ISSUE THREAD

**Issue by hibiken** [hibiken/asynq#77]
Experiment with other serialization format and benchmark performance and memory usage:

Other serialization format:

- msgpack
- protobuf

**Comment by cielu** [comment]
Hello, hibiken , how to use this lib in go-gin ?

**Comment by cielu** [comment]
Why I can't kill the process ?

**Comment by hibiken** [comment]
@cielu  Which OS are you using?

**Comment by cielu** [comment]
@hibiken  macOS, But I start the worker  in go-gin . Do you have any good idea ? thanks ..

I'm new at go

**Comment by hibiken** [comment]
So you are using [github.com/gin-gonic/gin](https://github.com/gin-gonic/gin) for your web framework, correct?
And are you starting the workers (`bg.Run(handler)`) from your web server's main?

**Comment by cielu** [comment]
@hibiken  Yes , that's right . Here is my main func code 

```
func main() {
	// Set Mode
	gin.SetMode(setting.AppCfg.AppMode)
	// Init router
	router := routes.InitRouter()
	// run
	router.Run(":" + setting.AppCfg.AppPost)
	// init asynq worker
	asynqWorker.InitAsynqWorker()
	// init asynq client
	asynqClient.InitAsynqClient()
}

```

**Comment by hibiken** [comment]
I see. 
The intended use case of `asynq` is that you use `Client` to schedule tasks to be processed in the background outside of a user request, and have another process(main.go) to process those tasks in the background. 
So you will create another `main.go` apart from your web server.

So for example, you will have something like this in your web server's main file:

```go
package main

import "github.com/gin-gonic/gin"

func main() {
	r := gin.Default()
        client := asynq.NewClient(/* redis conn opt */)
	r.POST("/signup", func(c *gin.Context) {
                t := asynq.NewTask("send_email", map[string]interface{}{"user_id": 42})
		client.Schedule(t, time.Now())
                // render html or json
	})
	r.Run() 
}
```

and create a separate `main.go`  file for workers:

```go
func main() {
    r := &asynq.RedisClientOpt{
        Addr: "localhost:6379",
    }

    bg := asynq.NewBackground(r, &asynq.Config{
        Concurrency: 10,
    })

    bg.Run(handler)
}
```

**Comment by cielu** [comment]
Yeah . enhh, I got what you mean . But , can i start the worker in one project ? I don't want separate it . 

thanks 😊

**Comment by hibiken** [comment]
I see. 

`Background.Run` method will block and wait for a termination signal (OS signal TERM or INTERRUPT). 

I think if you want to start the workers from your web server's main then try this:

```go
func main() {
	// Set Mode
	gin.SetMode(setting.AppCfg.AppMode)
	// Init router
	router := routes.InitRouter()

        bgDone := make(chan, struct{})

       go func() {
           bg := asynq.NewBackground(r, &asynq.Config{/* options */})
           bg.Run(handler)
           bgDone <- struct{}{}
       }()
	// run
	router.Run(":" + setting.AppCfg.AppPost)
        <-bgDone
}
```

If that doesn't work, then another option is to fork this repo and export `Background.Start` and `Background.Stop` methods (currently they are unexported) and call those to start and stop the background workers, those methods are non-blocking.

**Comment by cielu** [comment]
Ohh. Thank you very much !

**Comment by hibiken** [comment]
Closing this issue for now
