### ISSUE TITLE
[BUG] exec.Command with FFMPEG uses a lot of memory

### ISSUE THREAD

**Issue by jhemmmm** [hibiken/asynq#804]
**Describe the bug**
I am currently using exec.Command to run a ffmpeg to transcode a video. For some reason, the size of the video is being opened in the memory. For example, if you have a 10GB video file, my asynq server will have a 10GB memory.

**Comment by kamikazechaser** [comment]
This is not related to asynq. Review your handler implementation to take care of what it does.
