### ISSUE TITLE
v0.25.0 Release watch

### ISSUE THREAD

**Issue by kamikazechaser** [hibiken/asynq#811]
This is a tracker of when v0.25.0 is expected to be released.

Docs and dependencies:

- [x] Changelog updated
- [x] Core dependencies updated
- [ ] /x dependencies updated
- [ ] /tools dependencies updated
- [x] `base.go` Version

Pending PRs:

- [x] #758
- [x] #743
- [x] #742
- [x] #715
- [x] #708
- [x] #534

Pending Issues:

- [ ] #578

To test the latest changes, you can always install from the `@master` branch.

**Comment by shuqingzai** [comment]
Does #787 have any plans? @kamikazechaser

**Comment by kamikazechaser** [comment]
@shuqingzai I'd put it for the next release. Anyways after v0.25.0 I expect development and feature releases to be much much faster as we would have sorted some of the main blockers.

**Comment by xinjiayu** [comment]
I hope to add a feature that automatically sets the client name when asynq connects to redis, which makes it convenient to check the connection status of asynq on redis. Thank you.

**Comment by pior** [comment]
@kamikazechaser do you think https://github.com/hibiken/asynq/pull/868 can end up in this release?

This change is a significant performance improvement, and is pretty common practice.

**Comment by kamikazechaser** [comment]
@pior There are a few related issues/PRs to that. But most likely not. I'll post an update on this release by next week.

**Comment by pior** [comment]
All right 👍 
What should we expect for this PR (and the other you mention)? Will there be another release soon?

We would really prefer an active Asynq repo, to maintaining a fork 🙏

**Comment by kamikazechaser** [comment]
Just quick update, v0.25.0 will be prepped for release next week. You can expect it to be out within the next 2 weeks. Additionally, new major feature changes PRs will be first merged into the `unstable` branch so that users can test it out with `go get github.com/../..@unstable` without having to wait for a tagged release. `unstable` will be free of breaking changes.

**Comment by pior** [comment]
Sweet! 
What kind of changes would go to `unstable`? Would #868 be a good candidate?

**Comment by kamikazechaser** [comment]
Yeah, pretty much all new useful features that also need time for continuous feedback (smoke testing sort of branch).

**Comment by kamikazechaser** [comment]
I don't have permissions to push to forks. So, there is a bit of hold up on small issues that need resolving on those PRs. But by the end of the week I'll change the base, merge them on a different one so that we can proceed with closing this issue asap.

**Comment by cobain** [comment]
what's the plan of v0.25? It seems that many issues are needed to be fixed.

**Comment by hachi-zzq** [comment]
when release the v0.25?

**Comment by cobain** [comment]
lots of archived task are left in redis and cost memory all the time. So hope we can fix this issue asap.

**Comment by pior** [comment]
Also hoping to see some progress here 🙏

**Comment by logan-stytch** [comment]
Hey! We're thinking of using this library to build an async service but wanted to know the current status. I see there hasn't been much activity in the past six months, so we just wanted to know whether it's still being actively supported.

**Comment by pior** [comment]
@kamikazechaser @hibiken Do you think we can find a better maintenance model? 
I don't think this attempt is working well.

**Comment by kamikazechaser** [comment]
All the pending PRs have been merged with the exception of #534 (there is an issue with it). In any case, it is not a "must-have" feature at the moment.

I'll be adding other PR's as well for v0.25.0.

@pior I agree. I personally use of this library because of certain issue with Redis itself, But I want to see it up to date in any case. Do you have any ideas?

**Comment by pior** [comment]
@kamikazechaser sorry for the late response, but I did not want to answer this question too quickly.

I can dedicate a few hours per week to help you maintain Asynq. I want to push for stability, performance and code quality.

I think I can help by providing feedbacks to PR authors, doing some work myself (like what I already started doing).
I would then tag you on PRs for final review and merging.

For the v0.25.0 release: if we're ready, I can work on updating the deps, the changelog and the version.
I think we should scope out #578, because I'm not seeing a way to support older version of Go and keep the maintenance load low.

**Comment by kamikazechaser** [comment]
v0.25.0 will be released this week. In the meanwhile, anyone can test on the @master release and check if there are any issues. I have updated the `go-redis` package as well (Sometimes they introduce some unintended breaking changes).

Also please review #950 in case I have missed out any notable feature or fix.

The next "major" release (v0.26.0) may come next year around Feb (When 1.24 is released).

The `tools`, `x` packages depend on the module itself so we have to tag this release before upgrading those. Anyone who wishes to install those packages may have to use the @master tag so as to correctly pull in the latest code.

**Comment by pior** [comment]
I did not see anything missing from the changelog 👍

**Comment by kamikazechaser** [comment]
I'll add you last PR into the change-log as well. We can wait a day for anyone using `master` to report any issues found and release tomorrow.

**Comment by pior** [comment]
Thanks @kamikazechaser 💯
