### ISSUE TITLE
[QUESTION] How to delete tasks that have been archived and are not in the "asynq:{default}:archived" zset?

### ISSUE THREAD

**Issue by Ancxk** [hibiken/asynq#847]
Our project doesn't need to keep track of archived task lists. 
Due to lack of cleanup previously, there are already 2 million records of archived tasks with keys like 'asynq:{default}:t:*'.
The provided `Inspector.DeleteAllArchivedTasks()` function can only delete tasks associated with 'asynq:{default}:archived' zset, which has a maximum of 9999 entries.
Is it only to manually scan and delete archived tasks that are not listed in 'asynq:{default}:archived'?"

**Comment by cobain** [comment]
I met the same issue about archived task, which has 9999 entries currently.  we need a way to delete them.
