### ISSUE TITLE
Add example for redict.io and NATS jetstream

### ISSUE THREAD

**Issue by kharabela** [hibiken/asynq#863]
With recent redis license change.I feel there is need to add usage guidance for redict.io and NATS jetstream or postgressql. Please help me to understand if I want to replace redis with redict.io or NATS Jetstream  or postgresql what changes do I need to make

**Comment by kamikazechaser** [comment]
This library is tightly coupled with Redis. Only a pure Redis drop-in replacement will work. Redict.io should work.
