### ISSUE TITLE
[BUG] Reduce number of unnecessary dependencies

### ISSUE THREAD

**Issue by gunnsth** [hibiken/asynq#87]
**Is your feature request related to a problem? Please describe.**
When utilizing in my program, `go mod download` pulls in a large number of dependencies. Many of which are related to the nice but "optional" CLI tool.

**Describe the solution you'd like**
Move the CLI to a separate project such as asynq-cli or similar.
Or possibly create a separate nested go.mod file under the CLI folder.

**Describe alternatives you've considered**
Very nice and simple library. Would be nice if could be used with only the bare minimum of dependencies. Wanted to point this issue out since it was a bit of frustration when building the project multiple files in docker containers.

**Additional context**
N/A

**Comment by hibiken** [comment]
@gunnsth Thanks for opening this issue. 

Fix is in #89
