### ISSUE TITLE
[QUESTION] Is it safe to run multiple instances of worker?

### ISSUE THREAD

**Issue by gunnsth** [hibiken/asynq#88]
Is it safe to use 4x workers with for example concurrency 20 each? For example in a containerized environment, where each worker runs in its own container?

Just wondering because I did not see this addressed specifically in other questions or documentation.

**Comment by hibiken** [comment]
@gunnsth Thanks for opening an issue and asking this question.

You should be able to run multiple worker processes connecting to the same Redis instance and read from the same queue. Alternatively, you can run multiple worker processes with each reading from different queues.

There's  `asynqmon ps` command to list all workers processes.

Please let me know if you run into any issues!

**Comment by gunnsth** [comment]
Thanks.

**Comment by WSUFan** [comment]
Hi @hibiken. I have a follow-up question regarding running multiple instances of workers that serve the same queue. As we have a recovery mechanism now, could there be a possibility that several recovery processes pick up and re-enqueue the same lease expired task multiple times (so the queue will have multiple entries of the same task ID)?
