### ISSUE TITLE
[FEATURE REQUEST] Exposing MinIdleConns redis config

### ISSUE THREAD

**Issue by sprabowo** [hibiken/asynq#892]
**Is your feature request related to a problem? Please describe.**
I want to have MinIdleConns redis config for asynq initialization. since asynq uses go-redis@v9 that support MinIdleConns config then exposing this config might be possible to do

**Describe the solution you'd like**
Adding MinIdleConns redis config to asynq. there's an [open PR](https://github.com/hibiken/asynq/pull/891) from mine

**Comment by sprabowo** [comment]
kindly have a look ya @hibiken @kamikazechaser

**Comment by sprabowo** [comment]
bump this up. please help to review this @hibiken @kamikazechaser

**Comment by sprabowo** [comment]
can anyone help to review this?

**Comment by sprabowo** [comment]
can anyone help to review this?

**Comment by kamikazechaser** [comment]
@sprabowo I have documented an alternative, please try it out and let me know if it is sufficient.
