### ISSUE TITLE
[Question] the key " asynq:{default}:t:896da8b6-b489-429c-9f8b-cd0bdc9b7592 " will be store in redis forever ?

### ISSUE THREAD

**Issue by hachi-zzq** [hibiken/asynq#910]
hi, i see many keys like  asynq:{default}:t:896da8b6-b489-429c-9f8b-cd0bdc9b7592  in my redis , and these keys' TTL is null , so my question is :
these keys will be store in redis forever ? I am afraid that endless growth will cause redis memory overflow and affect the operation of the program. @hibiken

**Comment by pior** [comment]
Those keys are deleted when the task is done: https://github.com/hibiken/asynq/blob/master/internal/rdb/rdb.go#L325-L327
