### ISSUE TITLE
[FEATURE REQUEST] Support sqlite3 as alternative adaptor to valkey and redis

### ISSUE THREAD

**Issue by wakatara** [hibiken/asynq#919]
**Is your feature request related to a problem? Please describe.**

Yes, I need a task queue manager but would like to have fewer server dependencies so am hoping to only ise a slqite3 database for my entire app. It would be nice if asynq (which I am loving with valkey btw) could operate in that fashion.

**Describe the solution you'd like**

Swap out redis for sqlite.

**Describe alternatives you've considered**

Already used valkey as a drop in replacement but ultimately I'm hoping to have a "run local" approach to this without the need for extra or complex services for the queue.

**Additional context**

If rails 8 can do it, so should Go... =] 
Also, someone has done something similar with sqlite already  https://github.com/maragudk/goqite

**Comment by kamikazechaser** [comment]
This library is tightly coupled with the inner workings of redis (lua scripting, commands only found in redis and redis forks). There is a very low chance that existing abstractions over redis could even work.

**Comment by wakatara** [comment]
@kamikazechaser I suspected as much, but you know... never ask, never get. Thanks for entertaining the request though even if it's not possible.  =]

**Comment by wakatara** [comment]
@ixugo Looks interesting, I'll check it out. Thanks!
