### ISSUE TITLE
[BUG] handler did not run and this task hang out from then.

### ISSUE THREAD

**Issue by cobain** [hibiken/asynq#952]
**Describe the bug**
task enqueued successfully but I found that the handler did not executed. 
once it happened, all the other task  will not execute then.
When I restart the process, all the pending task runs one by one.

**To Reproduce**
Steps to reproduce the behavior (Code snippets if applicable):
1. Setup background processing ...
2. Enqueue tasks ...
3. See Error ...

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Linux]
 - Version of `asynq` package [e.g. v0.24.1]

**Additional context**

**Comment by cobain** [comment]
I use the default config. I don't know if it relates with this. When I have 10 kinds of task, it works well.
But after increase to be 15, it suddenly did not work. After restart, it works.
	// Specify how many concurrent workers to use
			Concurrency: 10,
			// Optionally specify multiple queues with different priority.
			Queues: map[string]int{
				"critical": 6,
				"default":  3,
				"low":      1,
			},

**Comment by kamikazechaser** [comment]
> After restart, it works.

With this info only, it is very difficult where this issue is originating from. But very less likely from the library. Use the inspector or CLI to try and debug and provide more info.

**Comment by cobain** [comment]
yes, I know.  it seems the worker died. when I kill the process, I don't now what to be triggered and the handler executed.

**Comment by cobain** [comment]
when I kill the process, it sends signals, then trigger the handler according to the doc. But I am not clearly about the worker.

Note: If you send TERM or INT signal without sending TSTP signal, the Server will start a timer for 8 seconds to allow for all workers to finish (To customize this timeout duration, use ShutdownTime config). If there are workers that didn't finish within that time frame, the task will be transitioned back to pending state and will be processed once the program restarts.

**Comment by cobain** [comment]
I found it works before 00:00, after 00:00, all the task will hang out.
before this, it has worked well for half an year.

**Comment by cobain** [comment]
another clue it that it happened after I added several task type. before it, I have 10 tasks type.
Now I have 14 tasks type

**Comment by cobain** [comment]
does it related with the config Concurrency: 10 ?

**Comment by cobain** [comment]
do you have any guess about the reason? I don't know why it happened after 00:00. do we have any code which executes clean or any tasks after 00:00?

**Comment by cobain** [comment]
ok. I will try it on test env firstly.

**Comment by cobain** [comment]
anyway, I have upgrade to be 0.25.0 and see if it would work tomorrow.

**Comment by cobain** [comment]
The bug still happened on 0.25.0. @kamikazechaser

**Comment by cobain** [comment]
@hibiken @appleboy @pior

**Comment by cobain** [comment]
does it relates with previous redis cache? now I need to  a way to fix issue. I could not restart the service every night. 😂

**Comment by pior** [comment]
If you post a simplified app, it will be easier to fix this issue.

**Comment by cobain** [comment]
my app is the same with the demo code and it runs for 2 years.
recently, I added several task. then it failed after 00:00.
I have upgraded to 0.25.0 and it still doesn't work.
Today I just set the log level to be debug. let me check the log tonight.

**Comment by cobain** [comment]
update:
it seems no useful debug logs currently. 
I have switched the redis db to a new one. and try again.

btw, I am investigating the source code. Hope i can fix it asap. 
@pior @hibiken @kamikazechaser @appleboy  hope you guys can provide some help or more details.

**Comment by kamikazechaser** [comment]
There are a lot of reasons for why you are encountering this issue. It's very difficult to reproduce without some sample code and/or redis info. I'd suggest you look at existing issues around the scheduler and archiving of tasks.

**Comment by cobain** [comment]
My code and config are same with the demo provided.  I just add 10+ task type and handler and registered.
last night, when I reproduced this issue after 00:00, I use the web tool and see the status was pending.

**Comment by cobain** [comment]
I finally get the root cause. It is caused by some 3rd party script.  It triggered a restart signal but not succeed. 
in the case, asynq got the signal and shutdown the server. so asynq would not work any more.
