### ISSUE TITLE
[QUESTION] How to access task ID within a task?

### ISSUE THREAD

**Issue by fargusplumdoodle** [hibiken/asynq#960]
ChatGPT keeps trying to reference `t.ID()` from the `*asynq.Task`, but that is not an option. Was this removed? 

I am hoping to include the Task ID in my logs.

Sorry about the bug label, I don't think this is a bug.

**Version**
I am running 24.1

**Comment by yousifh** [comment]
You should be able to use `asynq.GetTaskID(ctx)` in your handler code to get the task ID.
