### ISSUE TITLE
[BUG] RedisClient created by PeriodicTaskManager doesn't close connection

### ISSUE THREAD

**Issue by HuangShaoyan** [hibiken/asynq#975]
**Describe the bug**
asynq creates a scheduler using `NewScheduler` when invoking `NewPeriodicTaskManager`, setting `scheduler.sharedConnection` to false. However, `scheduler.client.sharedConnection` remains true. 
It will cause `Client.Close` to print `redis connection is shared so the Client can't be closed through asynq`.

**Environment:**
 - OS: MacOS
 - `asynq` v0.25.0
 - Redis 7.0

**To Reproduce**
1. Create a PeriodicTaskManager using `asynq.NewPeriodicTaskManager`.
2. Press Ctrl+C to stop the process.
3. Check the log output.

**Expected behavior**
asynq should set `scheduler.client.sharedConnection` to `false` when the Redis client is created by the PeriodicTaskManager itself.

**Comment by kamikazechaser** [comment]
Probably landed in #958. Pinging @daixijun as well.

**Comment by kamikazechaser** [comment]
I can reproduce it:

```bash
asynq: pid=20593 2024/12/03 05:57:22.303908 INFO: Scheduler starting
asynq: pid=20593 2024/12/03 05:57:22.303939 INFO: Scheduler timezone is set to UTC
asynq: pid=20593 2024/12/03 05:57:22.303945 INFO: Send signal TERM or INT to stop the scheduler
^Casynq: pid=20593 2024/12/03 05:57:22.781738 INFO: Scheduler shutting down
asynq: pid=20593 2024/12/03 05:57:22.783083 ERROR: Failed to close redis client connection: redis connection is shared so the Client can't be closed through asynq
asynq: pid=20593 2024/12/03 05:57:22.783122 INFO: Scheduler stopped
2024/12/03 08:57:42 graceful shutdown period exceeded, forcefully shutting down
exit status 1
```

**Comment by kamikazechaser** [comment]
@HuangShaoyan I have pushed a fix pending review. Could you try it out?

` go get github.com/hibiken/asynq@f1e7dc4056abaa6549bf014d2e6b67508437d236`

**Comment by HuangShaoyan** [comment]
I have tested the fix `f1e7dc`, and I can confirm that the bug has been resolved.
